[package]
name = "uasm"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = { version = "1.0", optional = true }
libc = "0.2"
cfgenius = "*"
intrusive-collections = "0.9"
errno = "*"
once_cell = "*"
[features]
default = ["riscv", "x86-v1", "x86-v2", "assembler"]
riscv = []
x86-v1 = []
x86-v2 = []
std = []
assembler = ["smallvec"]
jit = []

[build-dependencies]
git2 = "*"

