#!/usr/bin/env python3
"""RISC-V table generator for asmkit (vendored fork of riscv-opcodes' parser).

Inputs (see meta/README.md for pins):
  - riscv-opcodes @ c6edca7d8c3f92694963a0a0baeb511930fb2af4 (BSD-3-Clause), located via
    the RISCV_OPCODES env var, defaulting to the repo-root `riscv-opcodes/` clone.
    Reads extensions/rv*, arg_lut.csv, csrs.csv, csrs32.csv, causes.csv.
  - riscv-unified-db @ v0.1.0 (BSD-3-Clause-Clear), located via the RISCV_UNIFIED_DB
    env var, defaulting to the repo-root `riscv-unified-db/` clone. Only used for
    doc comments (see meta/docenizer_riscv.py); generation works without it.
  - src/riscv/opcodes.rs: the hand-maintained immediate section above the
    "Automatically generated" marker is preserved byte-identical.
  - src/riscv/assembler.rs: the `Encoding::* =>` arms of `emit_n` are parsed to learn
    the runtime operand order of every encoding variant (the order callers pass
    operands in). Variants without a parsable arm fall back to field order.

Outputs (written in-place, run rustfmt afterwards):
  - src/riscv/opcodes.rs  — MATCH/MASK consts, Opcode enum, Encoding, InstructionValue.
  - src/riscv/emitter.rs  — EmitterExplicit trait (methods return (), errors go
                            through Assembler::last_error).
  - src/riscv/instdb.rs   — instruction info database: per-opcode RW patterns,
                            memory access kind/width, implicit register effects,
                            implicit CSR flag effects, operand-class signatures.

Curated data maintained in this file (all documented at the point of definition):
  - EXCLUDED_EXTENSIONS: extension files whose encodings src/riscv/assembler.rs
    cannot emit yet (they would introduce new Encoding variants).
  - CSR_ACCESS, FSR_ACCESS, FENCE_NAMES, VOLATILE_NAMES, VXSAT_PREFIXES,
    IMPLICIT_REG_NAMES: semantic overrides the encodings alone cannot express.

Known modeling gaps (deliberate): reads/writes of the vtype/vl CSRs by vector
instructions and of vxrm by fixed-point vector instructions are not modeled —
core::rwinfo::CpuRwFlags has no bits for them (would need a core change).

Usage: python3 meta/riscv.py [extension-globs...]   (default: all supported rv*)
"""

import collections
import glob
import logging
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault("RISCV_OPCODES", os.path.join(REPO_ROOT, "riscv-opcodes"))
os.environ.setdefault("RISCV_UNIFIED_DB", os.path.join(REPO_ROOT, "riscv-unified-db"))

from constants import *
from docenizer_riscv import load_inst_docs

logging.basicConfig(level=logging.INFO, format="%(levelname)s:: %(message)s")

SRC_RISCV = os.path.join(REPO_ROOT, "src", "riscv")
GENERATED_MARKER = "/* Automatically generated by parse_opcodes */"

# Extension files excluded from generation: their instructions introduce Encoding
# variants that the hand-written emit_n in src/riscv/assembler.rs does not implement
# (lpad's bare-imm20, ssrdp's bare-rd_n0, the Zilsd/Zclsd even-register-pair pseudo
# encodings). Re-enable once emit support lands.
EXCLUDED_EXTENSIONS = {
    "rv_zicfilp",
    "rv_zicfiss",
    "rv32_zilsd",
    "rv32_zclsd",
}

# ---------------------------------------------------------------------------
# Curated semantic overrides (documented in the module docstring).
# ---------------------------------------------------------------------------

# CSR access of the `csr` immediate operand: csrrw always writes the CSR and reads
# it when rd != x0; csrrs/csrrc always read and write when rs1/uimm != 0. Both are
# modeled as RW. The pseudo-ops have fixed directions.
CSR_ACCESS = {
    "csrrw": "X", "csrrs": "X", "csrrc": "X",
    "csrrwi": "X", "csrrsi": "X", "csrrci": "X",
    "csrr": "R", "csrw": "W", "csrs": "X", "csrc": "X",
    "csrwi": "W", "csrsi": "X", "csrci": "X",
}

# FP CSR access pseudos: (read_flags, write_flags) using CpuRwFlags RISCV_* bits.
FSR_ACCESS = {
    "fsflags": ("FFLAGS", "FFLAGS"),
    "fsflagsi": ("FFLAGS", "FFLAGS"),
    "frflags": ("FFLAGS", "0"),
    "fsrm": ("FRM", "FRM"),
    "fsrmi": ("FRM", "FRM"),
    "frrm": ("FRM", "0"),
    "fscsr": ("FFLAGS | FRM", "FFLAGS | FRM"),
    "frcsr": ("FFLAGS | FRM", "0"),
}

# Instructions with no register effects at all (memory-ordering / hints).
FENCE_NAMES = {"fence", "fence_i", "fence_tso", "pause"}

# Instructions with machine-level side effects and no allocatable register effects.
VOLATILE_NAMES = {"ecall", "ebreak", "mret", "sret", "mnret", "dret", "wfi"}

# Vector instruction prefixes that write the vxsat CSR flag (saturating ops).
VXSAT_PREFIXES = ("vsadd", "vssub", "vaadd", "vasub", "vsmul", "vnclip")

# Implicit fixed-register effects keyed by instruction name: (read_mask, write_mask).
# Bits 0..31 name GP registers x0..x31, bit 32 names the vector mask register v0.
RA_BIT = 1 << 1
SP_BIT = 1 << 2
V0_BIT = 1 << 32
IMPLICIT_REG_NAMES = {
    "c_jal": (0, RA_BIT),      # link to ra
    "c_jalr": (0, RA_BIT),     # link to ra
    "c_addi16sp": (SP_BIT, SP_BIT),
    "c_addi4spn": (SP_BIT, 0),
    # sp-based compressed loads/stores: base address is sp.
    "c_lwsp": (SP_BIT, 0), "c_ldsp": (SP_BIT, 0),
    "c_flwsp": (SP_BIT, 0), "c_fldsp": (SP_BIT, 0),
    "c_swsp": (SP_BIT, 0), "c_sdsp": (SP_BIT, 0),
    "c_fswsp": (SP_BIT, 0), "c_fsdsp": (SP_BIT, 0),
}

# FP load/store instruction names (no fflags side effects, rd/rs2 are FP, rs1 is GP).
FP_LOADS = {"flw", "fld", "flh", "flq"}
FP_STORES = {"fsw", "fsd", "fsh", "fsq"}

# Compressed memory instructions: name -> (mem_access, width_in_bytes).
C_MEM = {
    "c_lw": ("LOAD", 4), "c_lwsp": ("LOAD", 4),
    "c_ld": ("LOAD", 8), "c_ldsp": ("LOAD", 8),
    "c_flw": ("LOAD", 4), "c_flwsp": ("LOAD", 4),
    "c_fld": ("LOAD", 8), "c_fldsp": ("LOAD", 8),
    "c_sw": ("STORE", 4), "c_swsp": ("STORE", 4),
    "c_sd": ("STORE", 8), "c_sdsp": ("STORE", 8),
    "c_fsw": ("STORE", 4), "c_fswsp": ("STORE", 4),
    "c_fsd": ("STORE", 8), "c_fsdsp": ("STORE", 8),
}


def process_enc_line(line, ext):
    """
    This function processes each line of the encoding files (rv*). As part of
    the processing, the function ensures that the encoding is legal through the
    following checks::

        - there is no over specification (same bits assigned different values)
        - there is no under specification (some bits not assigned values)
        - bit ranges are in the format hi..lo=val where hi > lo
        - value assigned is representable in the bit range
        - also checks that the mapping of arguments of an instruction exists in
          arg_lut.

    If the above checks pass, then the function returns a tuple of the name and
    a dictionary containing basic information of the instruction which includes:
        - variables: list of arguments used by the instruction whose mapping
          exists in the arg_lut dictionary
        - encoding: this contains the 32-bit encoding of the instruction where
          '-' is used to represent position of arguments and 1/0 is used to
          reprsent the static encoding of the bits
        - extension: this field contains the rv* filename from which this
          instruction was included
        - match: hex value representing the bits that need to match to detect
          this instruction
        - mask: hex value representin the bits that need to be masked to extract
          the value required for matching.
    """
    single_dict = {}

    # fill all bits with don't care. we use '-' to represent don't care
    # TODO: hardcoded for 32-bits.
    encoding = ["-"] * 32

    # get the name of instruction by splitting based on the first space
    [name, remaining] = line.split(" ", 1)

    # replace dots with underscores as dot doesn't work with C/Sverilog, etc
    name = name.replace(".", "_")

    # remove leading whitespaces
    remaining = remaining.lstrip()

    # check each field for it's length and overlapping bits
    # ex: 1..0=5 will result in an error --> x<y
    # ex: 5..0=0 2..1=2 --> overlapping bits
    for s2, s1, entry in fixed_ranges.findall(remaining):
        msb = int(s2)
        lsb = int(s1)

        # check msb < lsb
        if msb < lsb:
            logging.error(
                f'{line.split(" ")[0]:<10} has position {msb} less than position {lsb} in it\'s encoding'
            )
            raise SystemExit(1)

        # illegal value assigned as per bit width
        entry_value = int(entry, 0)
        if entry_value >= (1 << (msb - lsb + 1)):
            logging.error(
                f'{line.split(" ")[0]:<10} has an illegal value {entry_value} assigned as per the bit width {msb - lsb}'
            )
            raise SystemExit(1)

        for ind in range(lsb, msb + 1):
            # overlapping bits
            if encoding[31 - ind] != "-":
                logging.error(
                    f'{line.split(" ")[0]:<10} has {ind} bit overlapping in it\'s opcodes'
                )
                raise SystemExit(1)
            bit = str((entry_value >> (ind - lsb)) & 1)
            encoding[31 - ind] = bit

    # extract bit pattern assignments of the form hi..lo=val
    remaining = fixed_ranges.sub(" ", remaining)

    # do the same as above but for <lsb>=<val> pattern. single_fixed is a regex
    # expression present in constants.py
    for lsb, value, drop in single_fixed.findall(remaining):
        lsb = int(lsb, 0)
        value = int(value, 0)
        if encoding[31 - lsb] != "-":
            logging.error(
                f'{line.split(" ")[0]:<10} has {lsb} bit overlapping in it\'s opcodes'
            )
            raise SystemExit(1)
        encoding[31 - lsb] = str(value)

    # convert the list of encodings into a single string for match and mask
    match = "".join(encoding).replace("-", "0")
    mask = "".join(encoding).replace("0", "1").replace("-", "0")

    # check if all args of the instruction are present in arg_lut present in
    # constants.py
    args = single_fixed.sub(" ", remaining).split()
    encoding_args = encoding.copy()
    for a in args:
        if a not in arg_lut:
            parts = a.split("=")
            if len(parts) == 2:
                existing_arg, new_arg = parts
                if existing_arg in arg_lut:
                    arg_lut[a] = arg_lut[existing_arg]

                else:
                    logging.error(
                        f" Found field {existing_arg} in variable {a} in instruction {name} whose mapping in arg_lut does not exist"
                    )
                    raise SystemExit(1)
            else:
                logging.error(
                    f" Found variable {a} in instruction {name} whose mapping in arg_lut does not exist"
                )
                raise SystemExit(1)
        (msb, lsb) = arg_lut[a]
        for ind in range(lsb, msb + 1):
            # overlapping bits
            if encoding_args[31 - ind] != "-":
                logging.error(
                    f" Found variable {a} in instruction {name} overlapping {encoding_args[31 - ind]} variable in bit {ind}"
                )
                raise SystemExit(1)
            encoding_args[31 - ind] = a

    # update the fields of the instruction as a dict and return back along with
    # the name of the instruction
    single_dict["encoding"] = "".join(encoding)
    single_dict["variable_fields"] = args
    single_dict["extension"] = [os.path.basename(ext)]
    single_dict["match"] = hex(int(match, 2))
    single_dict["mask"] = hex(int(mask, 2))

    return (name, single_dict)


def same_base_isa(ext_name, ext_name_list):
    type1 = ext_name.split("_")[0]
    for ext_name1 in ext_name_list:
        type2 = ext_name1.split("_")[0]
        # "rv" mean insn for rv32 and rv64
        if (
            type1 == type2
            or (type2 == "rv" and (type1 == "rv32" or type1 == "rv64"))
            or (type1 == "rv" and (type2 == "rv32" or type2 == "rv64"))
        ):
            return True
    return False


def overlaps(x, y):
    x = x.rjust(len(y), "-")
    y = y.rjust(len(x), "-")

    for i in range(0, len(x)):
        if not (x[i] == "-" or y[i] == "-" or x[i] == y[i]):
            return False

    return True


def overlap_allowed(a, x, y):
    return x in a and y in a[x] or y in a and x in a[y]


def extension_overlap_allowed(x, y):
    return overlap_allowed(overlapping_extensions, x, y)


def instruction_overlap_allowed(x, y):
    return overlap_allowed(overlapping_instructions, x, y)


def create_inst_dict(file_filter, include_pseudo=False):
    """
    This function return a dictionary containing all instructions associated
    with an extension defined by the file_filter input. The file_filter input
    needs to be rv* file name with out the 'rv' prefix i.e. '_i', '32_i', etc.

    Each node of the dictionary will correspond to an instruction which again is
    a dictionary. The dictionary contents of each instruction includes:
        - variables: list of arguments used by the instruction whose mapping
          exists in the arg_lut dictionary
        - encoding: this contains the 32-bit encoding of the instruction where
          '-' is used to represent position of arguments and 1/0 is used to
          reprsent the static encoding of the bits
        - extension: this field contains the rv* filename from which this
          instruction was included
        - match: hex value representing the bits that need to match to detect
          this instruction
        - mask: hex value representin the bits that need to be masked to extract
          the value required for matching.

    In order to build this dictionary, the function does 2 passes over the same
    rv<file_filter> file. The first pass is to extract all standard
    instructions. In this pass, all pseudo ops and imported instructions are
    skipped. For each selected line of the file, we call process_enc_line
    function to create the above mentioned dictionary contents. Checks are
    performed in this function to ensure that the same instruction is not added
    twice to the overall dictionary.

    In the second pass, this function parses only pseudo_ops. For each pseudo_op
    this function checks if the dependent extension and instruction, both, exist
    before parsing it. The pseudo op is only added to the overall dictionary if
    the dependent instruction is not present in the dictionary, else it is
    skipped.
    """
    opcodes_dir = RISCV_OPCODES
    instr_dict = {}

    # file_names contains all files to be parsed in the riscv-opcodes directory
    file_names = []
    for fil in file_filter:
        file_names += glob.glob(f"{opcodes_dir}/extensions/{fil}")
    file_names = sorted(
        f for f in file_names if os.path.basename(f) not in EXCLUDED_EXTENSIONS
    )
    file_names.sort(reverse=True)
    # first pass if for standard/regular instructions
    logging.debug("Collecting standard instructions first")
    for f in file_names:
        logging.debug(f"Parsing File: {f} for standard instructions")
        if not os.path.isdir(f):
            with open(f) as fp:
                lines = (line.rstrip() for line in fp)  # All lines including the blank ones
                lines = list(line for line in lines if line)  # Non-blank lines
                lines = list(
                    line for line in lines if not line.startswith("#")
                )  # remove comment lines

            # go through each line of the file
            for line in lines:
                # if the an instruction needs to be imported then go to the
                # respective file and pick the line that has the instruction.
                # The variable 'line' will now point to the new line from the
                # imported file

                # ignore all lines starting with $import and $pseudo
                if "$import" in line or "$pseudo" in line:
                    continue
                logging.debug(f"     Processing line: {line}")

                # call process_enc_line to get the data about the current
                # instruction
                (name, single_dict) = process_enc_line(line, f)
                ext_name = os.path.basename(f)

                # if an instruction has already been added to the filtered
                # instruction dictionary throw an error saying the given
                # instruction is already imported and raise SystemExit
                if name in instr_dict:
                    var = instr_dict[name]["extension"]
                    if same_base_isa(ext_name, var):
                        # disable same names on the same base ISA
                        err_msg = f"instruction : {name} from "
                        err_msg += f"{ext_name} is already "
                        err_msg += f"added from {var} in same base ISA"
                        logging.error(err_msg)
                        raise SystemExit(1)
                    elif instr_dict[name]["encoding"] != single_dict["encoding"]:
                        # disable same names with different encodings on different base ISAs
                        err_msg = f"instruction : {name} from "
                        err_msg += f"{ext_name} is already "
                        err_msg += f"added from {var} but each have different encodings in different base ISAs"
                        logging.error(err_msg)
                        raise SystemExit(1)
                    instr_dict[name]["extension"].extend(single_dict["extension"])
                else:
                    for key in instr_dict:
                        item = instr_dict[key]
                        if (
                            overlaps(item["encoding"], single_dict["encoding"])
                            and not extension_overlap_allowed(
                                ext_name, item["extension"][0]
                            )
                            and not instruction_overlap_allowed(name, key)
                            and same_base_isa(ext_name, item["extension"])
                        ):
                            # disable different names with overlapping encodings on the same base ISA
                            err_msg = f"instruction : {name} in extension "
                            err_msg += f"{ext_name} overlaps instruction {key} "
                            err_msg += f'in extension {item["extension"]}'
                            logging.error(err_msg)
                            raise SystemExit(1)

                if name not in instr_dict:
                    # update the final dict with the instruction
                    instr_dict[name] = single_dict

    # second pass if for pseudo instructions
    logging.debug("Collecting pseudo instructions now")
    for f in file_names:
        logging.debug(f"Parsing File: {f} for pseudo_ops")
        if not os.path.isdir(f):
            with open(f) as fp:
                lines = (line.rstrip() for line in fp)  # All lines including the blank ones
                lines = list(line for line in lines if line)  # Non-blank lines
                lines = list(
                    line for line in lines if not line.startswith("#")
                )  # remove comment lines

            # go through each line of the file
            for line in lines:

                # ignore all lines not starting with $pseudo
                if "$pseudo" not in line:
                    continue
                logging.debug(f"     Processing line: {line}")

                # use the regex pseudo_regex from constants.py to find the dependent
                # extension, dependent instruction, the pseudo_op in question and
                # its encoding
                (ext, orig_inst, pseudo_inst, line) = pseudo_regex.findall(line)[0]
                ext_file = f"{opcodes_dir}/extensions/{ext}"

                # check if the file of the dependent extension exist. Throw error if
                # it doesn't
                if not os.path.exists(ext_file):
                    ext1_file = f"{opcodes_dir}/extensions/unratified/{ext}"
                    if not os.path.exists(ext1_file):
                        logging.error(
                            f"Pseudo op {pseudo_inst} in {f} depends on {ext} which is not available"
                        )
                        raise SystemExit(1)
                    else:
                        ext_file = ext1_file

                # check if the dependent instruction exist in the dependent
                # extension. Else throw error.
                found = False
                for oline in open(ext_file):
                    if not re.findall(f"^\\s*{orig_inst}\\s+", oline):
                        continue
                    else:
                        found = True
                        break
                if not found:
                    logging.error(
                        f"Orig instruction {orig_inst} not found in {ext}. Required by pseudo_op {pseudo_inst} present in {f}"
                    )
                    raise SystemExit(1)

                (name, single_dict) = process_enc_line(pseudo_inst + " " + line, f)
                # add the pseudo_op to the dictionary only if the original
                # instruction is not already in the dictionary.
                if orig_inst.replace(".", "_") not in instr_dict or include_pseudo:
                    # update the final dict with the instruction
                    if name not in instr_dict:
                        instr_dict[name] = single_dict
                        logging.debug(f"        including pseudo_ops:{name}")
                    else:
                        if single_dict["match"] != instr_dict[name]["match"]:
                            instr_dict[name + "_pseudo"] = single_dict

                        # if a pseudo instruction has already been added to the filtered
                        # instruction dictionary but the extension is not in the current
                        # list, add it
                        else:
                            ext_name = single_dict["extension"]

                        if (ext_name not in instr_dict[name]["extension"]) & (
                            name + "_pseudo" not in instr_dict
                        ):
                            instr_dict[name]["extension"].extend(ext_name)
                else:
                    logging.debug(
                        f"        Skipping pseudo_op {pseudo_inst} since original instruction {orig_inst} already selected in list"
                    )

    # third pass if for imported instructions
    logging.debug("Collecting imported instructions")
    for f in file_names:
        logging.debug(f"Parsing File: {f} for imported ops")
        with open(f) as fp:
            lines = (line.rstrip() for line in fp)  # All lines including the blank ones
            lines = list(line for line in lines if line)  # Non-blank lines
            lines = list(
                line for line in lines if not line.startswith("#")
            )  # remove comment lines

        # go through each line of the file
        for line in lines:
            # if the an instruction needs to be imported then go to the
            # respective file and pick the line that has the instruction.
            # The variable 'line' will now point to the new line from the
            # imported file

            # ignore all lines starting with $import and $pseudo
            if "$import" not in line:
                continue
            logging.debug(f"     Processing line: {line}")

            (import_ext, reg_instr) = imported_regex.findall(line)[0]
            import_ext_file = f"{opcodes_dir}/extensions/{import_ext}"

            # check if the file of the dependent extension exist. Throw error if
            # it doesn't
            if not os.path.exists(import_ext_file):
                ext1_file = f"{opcodes_dir}/extensions/unratified/{import_ext}"
                if not os.path.exists(ext1_file):
                    logging.error(
                        f"Instruction {reg_instr} in {f} cannot be imported from {import_ext}"
                    )
                    raise SystemExit(1)
                else:
                    ext_file = ext1_file
            else:
                ext_file = import_ext_file

            # check if the dependent instruction exist in the dependent
            # extension. Else throw error.
            found = False
            for oline in open(ext_file):
                if not re.findall(f"^\\s*{reg_instr}\\s+", oline):
                    continue
                else:
                    found = True
                    break
            if not found:
                logging.error(
                    f"imported instruction {reg_instr} not found in {ext_file}. Required by {line} present in {f}"
                )
                logging.error(f"Note: you cannot import pseudo/imported ops.")
                raise SystemExit(1)

            # call process_enc_line to get the data about the current
            # instruction
            (name, single_dict) = process_enc_line(oline, f)

            # if an instruction has already been added to the filtered
            # instruction dictionary throw an error saying the given
            # instruction is already imported and raise SystemExit
            if name in instr_dict:
                var = instr_dict[name]["extension"]
                if instr_dict[name]["encoding"] != single_dict["encoding"]:
                    err_msg = f"imported instruction : {name} in "
                    err_msg += f"{os.path.basename(f)} is already "
                    err_msg += f"added from {var} but each have different encodings for the same instruction"
                    logging.error(err_msg)
                    raise SystemExit(1)
                instr_dict[name]["extension"].extend(single_dict["extension"])
            else:
                # update the final dict with the instruction
                instr_dict[name] = single_dict
    return instr_dict


def to_camel_case(text):
    s = text.replace("-", " ").replace("_", " ")
    s = s.split()
    if len(text) == 0:
        return text
    return s[0] + "".join(i.capitalize() for i in s[1:])


def immediates(used_fields=None):
    """Immediate helpers keyed by merged field name. When `used_fields` is given,
    only immediates referenced by the selected instructions are emitted (arg_lut
    also carries fields of extensions we do not generate, e.g. the unratified P
    extension's p_* immediates, which have no Immediate fragment tables).
    """
    immediate_map = dict()
    for name, _ in arg_lut.items():
        if used_fields is not None and name not in used_fields:
            continue
        if "imm" in name:
            has_lo_or_hi = False
            if "lo" in name or "hi" in name:
                name = name.replace("lo", "").replace("hi", "")
                has_lo_or_hi = True
                name += "lohi"

            encoder = f"encode_immediate(&{name.upper()}, {name} as _)"
            typ = f"{"u32" if 'u' in name else "i32"}"
            immediate_map[name] = (encoder, typ)
    return immediate_map


def sanitize_field(arg):
    return arg.replace("=", "_eq_").replace(" ", "_")


def encoding_name(fields):
    """Name of the Encoding variant for a variable-field list (mirrors the enum)."""
    name = to_camel_case("_".join(sanitize_field(f).title() for f in fields))
    return name if name else "Empty"


def enum_name(instr_name):
    return instr_name.upper().replace("_", "")


def doc_key(instr_name):
    """Dotted mnemonic used for OPCODE_STR and unified-db doc lookup."""
    s = instr_name.lower().replace("c_", "c.").replace("cm_", "cm.")
    return s.replace("_", ".")


def emitter_arity(fields):
    """Number of operands of the generated emitter method (hi/lo pairs merged)."""
    seen = set()
    count = 0
    for field in fields:
        field = sanitize_field(field)
        if "imm" in field:
            if "lo" in field or "hi" in field:
                field = field.replace("hi", "").replace("lo", "") + "lohi"
            if field in seen:
                continue
            seen.add(field)
        count += 1
    return count


# ---------------------------------------------------------------------------
# Effects derivation (instdb.rs).
# ---------------------------------------------------------------------------

# OpRwFlags values used in the generated RW patterns (kept in sync with
# crate::core::rwinfo::OpRwFlags; asserted by instdb unit tests).
R, W, X = "R", "W", "X"
MEM_BASE = "B"  # READ | MEM_BASE_READ (address base register of a memory access)
NONE = "0"

WRITE_FIELDS = {"rd", "rd_n0", "rd_n2", "rd_p", "vd"}
RW_FIELDS = {"rd_rs1", "rd_rs1_n0", "rd_rs1_p"}
READ_VEC_FIELDS = {"vs1", "vs2", "vs3"}
READ_GP_PREFIXES = ("rs1", "rs2", "c_rs1", "c_rs2", "c_sreg")


def parse_emit_arm_orders(assembler_path):
    """Parses the `Encoding::<Variant> => { ... }` arms of `Assembler::emit_n` to
    learn the runtime operand order of every encoding variant. Positions are
    resolved to actual instruction field names through the `inst.set_<field>(...)`
    calls of each arm (bound variables are traced back to their `ops[N]` source);
    positions only read as immediates/labels stay generic 'imm' placeholders.
    Variants whose arm is `todo!()` are skipped (callers fall back to field order).
    """
    with open(assembler_path) as fp:
        text = fp.read()
    orders = {}
    for m in re.finditer(r"Encoding::(\w+) => \{(.*?)\n            \}", text, re.S):
        variant, body = m.group(1), m.group(2)
        if "todo!()" in body:
            continue
        # variable bindings: `let x = ops[N]...` / `let x = if ops[N]...`
        lets = {}
        for lm in re.finditer(r"let (\w+) = (?:if )?ops\[(\d+)\]", body):
            lets[lm.group(1)] = int(lm.group(2))
        # field assignments: `set_<field>(<var>)` / `set_<field>(ops[N])`
        field_at = {}
        for sm in re.finditer(r"set_(\w+)\((\w+)", body):
            field, var = sm.group(1), sm.group(2)
            if var in lets:
                field_at[lets[var]] = field
        for sm in re.finditer(r"set_(\w+)\(ops\[(\d+)\]", body):
            field_at[int(sm.group(2))] = sm.group(1)
        positions = {int(pm.group(1)) for pm in re.finditer(r"ops\[(\d+)\]", body)}
        spec = []
        for pos in range(max(positions, default=-1) + 1):
            spec.append(field_at.get(pos) or next((v for v, p in lets.items() if p == pos), "imm"))
        orders[variant] = spec
    return orders


def base_field(field):
    return field.split("_eq_")[0]


def field_access(field):
    """Read/write access of an operand field: R, W, X (RW), or None (no effects)."""
    base = base_field(field)
    if base in WRITE_FIELDS:
        return W
    if base in RW_FIELDS:
        return X
    if base in READ_VEC_FIELDS or base.startswith(READ_GP_PREFIXES):
        return R
    return None


# Prefix aliases matching emit_n arm variable names to actual instruction field
# names (arm code uses `rd`/`rs1`/`rs2` for the compressed prime/combined fields
# like rd_p, rs1_n0, rd_rs1_n0, c_rs2_n0).
FIELD_ALIASES = {
    "rd": ("rd",),
    "rs1": ("rs1", "c_rs1"),
    "rs2": ("rs2", "c_rs2"),
}


def match_arm_field(arm_name, field):
    prefixes = FIELD_ALIASES.get(arm_name, (arm_name,))
    return any(field == p or field.startswith(p + "_") for p in prefixes)


def operand_spec(name, fields, arm_orders):
    """Ordered operand spec for an instruction: field names (or 'imm') in the order
    callers pass them, matching emit_n's arms; padded with immediate placeholders
    up to the emitter arity (operands the arm does not consume, e.g. AMO aq/rl or
    the nf segment field). Falls back to field order for unimplemented arms.
    """
    fields = [sanitize_field(f) for f in fields]
    arity = emitter_arity(fields)
    if arm_orders.get(variant_of(fields)):
        arm_spec = list(arm_orders[variant_of(fields)])
        # Map the arm's variable names to the instruction's actual fields (the arm
        # order defines the operand order; field names drive access and classes).
        claimed, spec = set(), []
        for arm_name in arm_spec:
            if arm_name == "imm":
                spec.append("imm")
                continue
            match = next((f for f in fields if f not in claimed and f == arm_name), None)
            if match is None:
                match = next(
                    (f for f in fields if f not in claimed and match_arm_field(arm_name, f)),
                    arm_name,
                )
            claimed.add(match)
            spec.append(match)
        # Assign the actual immediate field names (hi/lo fragments merged, in field
        # order) to the arm's generic imm positions; fields the arm does not
        # consume (AMO aq/rl, the nf segment field) keep their positions at the end.
        leftover, seen_split = [], set()
        for f in fields:
            if f in claimed:
                continue
            # aq/rl are consumed together as the arm's merged aqrl immediate.
            if f in ("aq", "rl") and "aqrl" in spec:
                continue
            if "imm" in f and ("lo" in f or "hi" in f):
                f = f.replace("hi", "").replace("lo", "") + "lohi"
                if f in spec or f in seen_split:
                    continue
                seen_split.add(f)
            leftover.append(f)
        it = iter(leftover)
        spec = [next(it, "imm") if f == "imm" else f for f in spec]
        spec += list(it)
        spec += ["imm"] * (arity - len(spec))
        return spec
    # Fallback: fields in encoding order with split hi/lo immediates merged last.
    spec, split_imm = [], False
    for field in fields:
        if "imm" in field and ("lo" in field or "hi" in field):
            split_imm = True
            continue
        spec.append(field)
    if split_imm:
        spec.append("imm")
    spec += ["imm"] * (arity - len(spec))
    return spec


def variant_of(fields):
    return encoding_name(fields)


def vector_mem(name):
    """Memory access of vector load/store instructions: (kind, width); width 0
    means the access size is not instruction-fixed (whole-register loads/stores).
    """
    if re.match(r"^vl\d+re\d+_v$", name):
        return ("LOAD", 0)
    if re.match(r"^vs\d+r_v$", name):
        return ("STORE", 0)
    m = re.match(r"^(vl|vs)\w*?[ei](\d+)(?:ff)?_v$", name)
    if m:
        return ("LOAD" if m.group(1) == "vl" else "STORE", max(1, int(m.group(2)) // 8))
    return None


def scalar_mem(name, match):
    """Memory access derived from the static match bits: major opcode selects the
    load/store/AMO space, funct3 encodes the access width.
    """
    opcode, funct3, funct5 = match & 0x7F, (match >> 12) & 7, (match >> 27) & 0x1F
    if opcode == 0x03:  # LOAD: lb/lh/lw/ld + zero-extending variants
        return ("LOAD", (1, 2, 4, 8, 1, 2, 4, 0)[funct3])
    if opcode == 0x07:  # LOAD-FP: flh/flw/fld/flq
        return ("LOAD", (1 << funct3) if 1 <= funct3 <= 4 else 0)
    if opcode == 0x23:  # STORE: sb/sh/sw/sd
        return ("STORE", (1, 2, 4, 8, 0, 0, 0, 0)[funct3])
    if opcode == 0x27:  # STORE-FP: fsh/fsw/fsd/fsq
        return ("STORE", (1 << funct3) if 1 <= funct3 <= 4 else 0)
    if opcode == 0x2F:  # AMO: lr reads, sc writes, everything else read-modify-write
        width = (1 << funct3) if funct3 <= 4 else 0
        if funct5 == 0b00010:
            return ("LOAD", width)
        if funct5 == 0b00011:
            return ("STORE", width)
        return ("RMW", width)
    return None


def mem_access(name, match):
    if name in C_MEM:
        return C_MEM[name]
    if name.startswith("v"):
        vec = vector_mem(name)
        if vec is not None:
            return vec
    if name.startswith(("c_", "cm_")):
        return None
    return scalar_mem(name, match)


def is_fp_mnemonic(name):
    return name.startswith("f") and not name.startswith("fence")


def cpu_flags(name, fields, mem):
    """Implicit CSR flag effects as (read_flags, write_flags) bit names."""
    read_flags, write_flags = set(), set()
    if name in FSR_ACCESS:
        for flags, target in ((FSR_ACCESS[name][0], read_flags), (FSR_ACCESS[name][1], write_flags)):
            target.update(f for f in flags.split(" | ") if f != "0")
        return read_flags, write_flags
    if is_fp_mnemonic(name):
        # FP compute writes fflags; moves/sign-inject/classify and memory ops don't.
        if mem is None and not name.startswith(("fmv", "fsgnj", "fclass")):
            write_flags.add("FFLAGS")
        # An rm field selects the rounding mode; rm=7 reads it dynamically from frm.
        if "rm" in fields:
            read_flags.add("FRM")
    if name.startswith("v"):
        if name.startswith(VXSAT_PREFIXES):
            write_flags.add("VXSAT")
    return read_flags, write_flags


def implicit_regs(name, fields):
    read_mask, write_mask = IMPLICIT_REG_NAMES.get(name, (0, 0))
    # Masked vector instructions (vm=0) read v0 as the mask register.
    if "vm" in fields:
        read_mask |= V0_BIT
    return read_mask, write_mask


def operand_classes(name, spec, mem, spec_access):
    """Operand class per position for debug asserts: GP, FP, VEC, or IMM."""
    is_fp = is_fp_mnemonic(name) and name not in FSR_ACCESS
    is_c_fp = name.startswith("c_f")
    classes = []
    for field, access in zip(spec, spec_access):
        base = base_field(field)
        if field == "imm" or access is None or base == "csr":
            classes.append("IMM")
            continue
        if base in ("vd", "vs1", "vs2", "vs3"):
            classes.append("VEC")
            continue
        cls = "GP"
        if is_fp or is_c_fp:
            cls = "FP"
            if access == MEM_BASE:  # address base of FP loads/stores
                cls = "GP"
            elif base == "rd" and name.startswith(("feq_", "flt_", "fle_", "fclass_")):
                cls = "GP"
            elif base == "rd" and re.match(r"^fcvt_(w|wu|l|lu)_", name):
                cls = "GP"
            elif base == "rs1" and re.match(r"^fcvt_[sdqh]_(w|wu|l|lu)$", name):
                cls = "GP"
            elif base == "rd" and name.startswith("fmv_x_"):
                cls = "GP"
            elif base == "rs1" and re.match(r"^fmv_[sdqh]_x$", name):
                cls = "GP"
            elif base == "rs2" and name in FP_STORES:
                cls = "FP"
        if name in ("vmv_x_s", "vcpop_m", "vfirst_m") and base == "rd":
            cls = "GP"
        elif name == "vmv_s_x" and base == "rs1":
            cls = "GP"
        elif name == "vfmv_f_s" and base == "rd":
            cls = "FP"
        elif name == "vfmv_s_f" and base == "rs1":
            cls = "FP"
        classes.append(cls)
    return classes


def derive_effects(instr_dict, arm_orders):
    """Derives per-instruction effects. Returns {name: effect-dict} plus stats."""
    stats = collections.Counter()
    effects = {}
    for name, single in instr_dict.items():
        fields = single["variable_fields"]
        match = int(single["match"], 0)
        spec = operand_spec(name, fields, arm_orders)

        if name in FENCE_NAMES or name in VOLATILE_NAMES:
            spec_access = [None] * len(spec)
            stats["override"] += 1
        else:
            spec_access = [field_access(f) for f in spec]
            stats["rule"] += 1
        if name in CSR_ACCESS:
            stats["override"] += 1
            stats["rule"] -= 1

        mem = mem_access(name, match)
        if mem is not None:
            # The explicit base register (rs1) of the memory access is read.
            for i, f in enumerate(spec):
                if base_field(f).startswith(("rs1",)) and spec_access[i] == R:
                    spec_access[i] = MEM_BASE
                    break
            stats[f"mem_{mem[0].lower()}"] += 1
            if mem[1] == 0:
                stats["mem_width_unknown"] += 1

        csr = CSR_ACCESS.get(name)
        if csr is not None:
            for i, f in enumerate(spec):
                if base_field(f) == "csr":
                    spec_access[i] = csr

        read_flags, write_flags = cpu_flags(name, fields, mem)
        implicit = implicit_regs(name, fields)
        classes = operand_classes(name, spec, mem, spec_access)
        spec_access = [a if a is not None else NONE for a in spec_access]

        effects[name] = {
            "spec": spec,
            "access": spec_access,
            "classes": classes,
            "mem": mem,
            "read_flags": read_flags,
            "write_flags": write_flags,
            "implicit": implicit,
            "volatile": name in VOLATILE_NAMES,
        }
    return effects, stats


# ---------------------------------------------------------------------------
# Doc comments (riscv-unified-db, see meta/docenizer_riscv.py).
# ---------------------------------------------------------------------------


def doc_comment(instr_name, spec, docs):
    """`///` lines for an instruction: long name + description + assembly from
    riscv-unified-db, or a syntax fallback line when undocumented there.
    """
    key = doc_key(instr_name)
    doc = docs.get(key) or docs.get(key.removesuffix(".rv32"))
    if doc and (doc.get("long_name") or doc.get("description")):
        lines = []
        if doc.get("long_name"):
            lines.append(doc["long_name"])
        if doc.get("description"):
            lines.append("")
            lines.extend(doc["description"].split("\n"))
        if doc.get("assembly"):
            lines.extend(["", f"Assembly: `{key} {doc['assembly']}`"])
        return lines, True
    if doc and doc.get("assembly"):
        # undocumented in the DB, but its assembly syntax is known
        return [f"Assembly: `{key} {doc['assembly']}`"], True
    syntax = " ".join([key] + spec)
    return [f"Syntax: `{syntax}`"], False


def rust_doc(lines, indent=""):
    return "".join(f"{indent}/// {line}\n" if line else f"{indent}///\n" for line in lines)


# ---------------------------------------------------------------------------
# Rust emission.
# ---------------------------------------------------------------------------

ATTRIBUTION = """\
/* Automatically generated by parse_opcodes (meta/riscv.py). Do not edit by hand.
 * Derived from riscv-opcodes (BSD-3-Clause) and riscv-unified-db
 * (BSD-3-Clause-Clear); see meta/README.md for the input pins. */
"""


def make_encoders(instr_dict, docs):
    """Emits the EmitterExplicit trait (src/riscv/emitter.rs)."""
    out = f"""\
use super::opcodes::*;
use crate::core::emitter::*;
use crate::core::operand::*;

{ATTRIBUTION}
pub trait EmitterExplicit: Emitter {{
"""
    doc_hits = 0
    for i in instr_dict:
        args = instr_dict[i]["variable_fields"]
        nargs = emitter_arity(args)
        comment, hit = doc_comment(i, operand_spec_fallback(i, args), docs)
        doc_hits += hit
        out += rust_doc(comment, "    ")
        params = ", ".join(f"op{p}: impl OperandCast" for p in range(nargs))
        ops = ", ".join(f"op{p}.as_operand()" for p in range(nargs))
        out += f"    fn {i.lower()}(&mut self{', ' if params else ''}{params}) {{\n"
        out += f"        self.emit_n(Opcode::{enum_name(i)} as i64, &[{ops}])\n    }}\n"
    out += "}\n"
    logging.info(f"emitter docs: {doc_hits}/{len(instr_dict)} instructions documented")
    return out


def operand_spec_fallback(name, fields):
    """Field-order operand list used only for doc fallback syntax lines."""
    spec, split = [], False
    for field in fields:
        field = sanitize_field(field)
        if "imm" in field and ("lo" in field or "hi" in field):
            split = True
            continue
        spec.append(field)
    if split:
        spec.append("imm")
    return spec


def make_opcodes(instr_dict, docs):
    """Emits the generated tail of src/riscv/opcodes.rs (everything below the
    hand-maintained immediate section, which is preserved byte-identical)."""
    out = GENERATED_MARKER + "\n" + ATTRIBUTION + "\n"

    for i in instr_dict:
        out += f'pub const MATCH_{i.upper().replace(".", "_")}: u32 = {(instr_dict[i]["match"])};\n'
        out += f'pub const MASK_{i.upper().replace(".", "_")}: u32 = {(instr_dict[i]["mask"])};\n'
    for num, name in csrs + csrs32:
        out += f"pub const CSR_{name.upper()}: u16 = {hex(num)};\n"
    for num, name in causes:
        out += f'pub const CAUSE_{name.upper().replace(" ", "_")}: u8 = {hex(num)};\n'

    short_count = sum(1 for i in instr_dict if i.lower().startswith("c"))

    rv32ext, rv64ext = set(), set()
    for i in instr_dict:
        for ext in instr_dict[i]["extension"]:
            if ext.startswith("rv32"):
                rv32ext.add(i)
            elif ext.startswith("rv64"):
                rv64ext.add(i)
            else:
                # append to both lists, we can match these opcodes on both ISAs
                rv32ext.add(i)
                rv64ext.add(i)

    def match_table(name, ty, exts=None, compressed=False):
        s = f"pub static {name}: [{ty}; {len(instr_dict)}] = [\n"
        for i in instr_dict:
            if exts is not None and i not in exts:
                s += f"0xffff_ffff, /* {i} */\n"
            elif compressed:
                if i.lower().startswith("c"):
                    s += f"{int(instr_dict[i]['mask' if 'MASK' in name else 'match'], 16) & 0xFFFF},\n"
                else:
                    s += "0,\n"
            else:
                s += f"{instr_dict[i]['match' if 'MATCH' in name else 'mask']}, /* {i} */\n"
        return s + "];\n"

    out += match_table("OPCODE32_MATCH", "u32", rv32ext)
    out += match_table("OPCODE32_MASK", "u32", rv32ext)
    out += match_table("OPCODE64_MATCH", "u32", rv64ext)
    out += match_table("OPCODE64_MASK", "u32", rv64ext)
    out += match_table("OPCODE_MATCH", "u32")
    out += match_table("OPCODE_MASK", "u32")
    out += match_table("OPCODE_MASK_COMPRESSED", "u16", compressed=True)
    out += match_table("OPCODE_MATCH_COMPRESSED", "u16", compressed=True)

    out += f"\npub static ALL_OPCODES: [Opcode; {len(instr_dict)}] = [\n"
    for i in instr_dict:
        out += f"Opcode::{enum_name(i)},\n"
    out += "];\n"

    out += f"\npub static SHORT_OPCODE: [bool; {len(instr_dict)}] = [\n"
    for i in instr_dict:
        out += f"{str(i.lower().startswith('c')).lower()},\n"
    out += "];\n"

    out += f"pub const SHORT_OPCODES: [Opcode; {short_count}] = [\n"
    for i in instr_dict:
        if i.lower().startswith("c"):
            out += f"Opcode::{enum_name(i)},\n"
    out += "];\n"

    out += "#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]\n#[repr(u32)]\n"
    out += "pub enum Opcode {\n"
    doc_hits = 0
    for i in instr_dict:
        comment, hit = doc_comment(i, operand_spec_fallback(i, instr_dict[i]["variable_fields"]), docs)
        doc_hits += hit
        out += rust_doc(comment, "    ")
        out += f"    {enum_name(i)},\n"
    out += "    Invalid,\n}\n\n"
    logging.info(f"opcode docs: {doc_hits}/{len(instr_dict)} instructions documented")

    out += "pub const OPCODE_STR: &[&str] = &[\n"
    for i in instr_dict:
        out += f'    "{doc_key(i)}",\n'
    out += '    "<invalid>",\n];\n'

    out += """
#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub struct Inst {
    pub opcode: u32,
    pub funct3: u32,
    pub rs1: u32,
    pub rs2: u32,
    pub csr: i64,
    pub funct7: u32,
}

impl Inst {
    pub const fn encode(&self) -> InstructionValue {
        InstructionValue::new(
            0 | (self.funct7 << 25)
                | (self.rs2 << 20)
                | (self.rs1 << 15)
                | (self.funct3 << 12)
                | self.opcode,
        )
    }

    pub const fn new(op: Opcode) -> Self {
        match op {
            Opcode::Invalid => unreachable!(),
"""
    for i in instr_dict:
        enc_match = int(instr_dict[i]["match"], 0)
        opcode = (enc_match >> 0) & ((1 << 7) - 1)
        funct3 = (enc_match >> 12) & ((1 << 3) - 1)
        rs1 = (enc_match >> 15) & ((1 << 5) - 1)
        rs2 = (enc_match >> 20) & ((1 << 5) - 1)
        csr = (enc_match >> 20) & ((1 << 12) - 1)
        funct7 = (enc_match >> 25) & ((1 << 7) - 1)
        out += f"""            Opcode::{enum_name(i)} => Inst {{
                opcode: {hex(opcode)},
                funct3: {hex(funct3)},
                rs1: {hex(rs1)},
                rs2: {hex(rs2)},
                csr: {hex(csr)},
                funct7: {hex(funct7)},
            }},
"""
    out += "        }\n    }\n}\n"

    # Encoding enum + Opcode::encoding(): variants are named after the
    # variable-field lists (camel-cased).
    encodings = dict()
    for i in instr_dict:
        args = instr_dict[i]["variable_fields"]
        encoding = encoding_name(args)
        encodings.setdefault(encoding, []).append(enum_name(i))

    out += """
#[derive(Copy, Clone, PartialEq, Eq, Debug, Hash)]
pub enum Encoding {
"""
    for e in sorted(encodings):
        out += f"    {e},\n"
    out += "}\n"

    out += """
impl Opcode {
    pub fn encoding(self) -> Encoding {
        use Opcode::*;
        match self {
            Opcode::Invalid => unreachable!(),
"""
    for e in sorted(encodings):
        ops = encodings[e]
        out += "            " + "\n            | ".join(ops) + f"\n            => Encoding::{e},\n"
    out += "        }\n    }\n}\n"

    insn_value = """
/// InstructionValue contains the 32-bit instruction value and also provides access into the desired field.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct InstructionValue {
    pub value: u32,
}

impl InstructionValue {
    pub const fn new(value: u32) -> Self {
        Self { value }
    }

    pub const fn field<const FIELD_START: usize, const FIELD_SIZE: usize>(self) -> u32 {
        (self.value >> FIELD_START) & ((1 << FIELD_SIZE) - 1)
    }

"""

    for name, rng in arg_lut.items():
        sanitized_name = name.replace(" ", "_").replace("=", "_eq_")
        begin, end = rng[1], rng[0]
        mask = ((1 << (end - begin + 1)) - 1) << begin
        field = f"INSN_FIELD_{sanitized_name.upper()}"
        out += f"pub const {field}: u32 = {hex(mask)};\n"
        out += f"pub const {field}_START: u32 = {begin};\n"
        out += f"pub const {field}_SIZE: u32 = {(end - begin) + 1};\n"

        if "imm" in sanitized_name:
            sanitized_name += "_raw"

        insn_value += f"""    pub const fn {sanitized_name}(self) -> u32 {{
        (self.value >> {field}_START) & ((1 << {field}_SIZE) - 1)
    }}

    pub const fn set_{sanitized_name}(mut self, value: u32) -> Self {{
        let mask = {field};
        self.value &= !mask;
        self.value |= (value & ((1 << {field}_SIZE) - 1)) << {field}_START;
        self
    }}
"""

    used_fields = set()
    for single in instr_dict.values():
        used_fields.update(single["variable_fields"])
    imms = immediates(used_fields)
    for name in imms.keys():
        encoder, ty = imms[name]
        sanitized_name = name.replace(" ", "_").replace("=", "_eq_")
        insn_value += f"""
    /// {name}
    pub const fn {sanitized_name}(self) -> {ty} {{
        decode_immediate(&{sanitized_name.upper()}, self.value as _) as _
    }}

    pub const fn set_{sanitized_name}(mut self, {name}: {ty}) -> Self {{
        self.value |= encode_immediate(&{sanitized_name.upper()}, {name} as _);
        self
    }}
"""
    insn_value += "}\n"
    return out + insn_value


def make_instdb(instr_dict, effects, stats):
    """Emits src/riscv/instdb.rs: deduplicated, pattern-indexed static tables."""

    def pattern_key(e):
        return tuple((e["access"] + [NONE] * 6)[:6])

    def signature_key(e):
        return tuple((e["classes"] + ["ANY"] * 6)[:6])

    patterns, signatures, implicits = [], [], [(0, 0)]
    pattern_index, signature_index, implicit_index = {}, {}, {(0, 0): 0}
    for e in effects.values():
        for table, index, key in (
            (patterns, pattern_index, pattern_key(e)),
            (signatures, signature_index, signature_key(e)),
        ):
            if key not in index:
                index[key] = len(table)
                table.append(key)
        if e["implicit"] not in implicit_index:
            implicit_index[e["implicit"]] = len(implicits)
            implicits.append(e["implicit"])

    out = f"""\
//! RISC-V instruction info database: per-opcode effects.
//!
//! For every [`Opcode`] this records the operand read/write pattern (indexed into
//! [`RW_PATTERN_TABLE`]), the operand-class signature for debug asserts
//! ([`SIGNATURE_TABLE`]), the memory access kind and width, implicit fixed-register
//! effects ([`IMPLICIT_REG_TABLE`]), and implicit CSR flag effects
//! (`read_flags`/`write_flags`, `CpuRwFlags::RISCV_*` bits).
//!
//! Modeling notes:
//! - The operand order follows `Assembler::emit_n` (the order callers pass
//!   operands), not the bit-field order of the encoding.
//! - The `csr` immediate operand of CSR instructions carries R/W bits describing
//!   the CSR access itself.
//! - Vector instructions with a `vm` field conservatively read v0 (vm=0 masking);
//!   reads/writes of vtype/vl/vxrm are not modeled (`CpuRwFlags` has no bits).
//! - `mem_width` is the access width in bytes; 0 means no memory access or a width
//!   that is not instruction-fixed (whole-register vector loads/stores).
//!
//! Automatically generated by parse_opcodes (meta/riscv.py). Do not edit by hand.
//! Derived from riscv-opcodes (BSD-3-Clause) and riscv-unified-db
//! (BSD-3-Clause-Clear); see meta/README.md for the input pins.
use crate::core::rwinfo::{{CpuRwFlags, OpRwFlags}};

use super::opcodes::Opcode;

/// Pattern value: no effects.
pub const NONE: u32 = 0;
/// Pattern value: operand is read (`OpRwFlags::READ`).
pub const R: u32 = OpRwFlags::READ.bits();
/// Pattern value: operand is written (`OpRwFlags::WRITE`).
pub const W: u32 = OpRwFlags::WRITE.bits();
/// Pattern value: operand is read and written (`OpRwFlags::RW`).
pub const X: u32 = OpRwFlags::RW.bits();
/// Pattern value: memory address base register, read (`OpRwFlags::READ | MEM_BASE_READ`).
pub const B: u32 = OpRwFlags::READ.bits() | OpRwFlags::MEM_BASE_READ.bits();

/// No memory access (`InstInfo::mem_access`).
pub const MEM_NONE: u8 = 0;
/// Memory load (`InstInfo::mem_access`).
pub const MEM_LOAD: u8 = 1;
/// Memory store (`InstInfo::mem_access`).
pub const MEM_STORE: u8 = 2;
/// Atomic memory read-modify-write (`InstInfo::mem_access`).
pub const MEM_READ_MODIFY_WRITE: u8 = 3;

/// `InstInfo::flags` bit: machine-level side effects, no allocatable effects
/// (ecall/ebreak/xret/wfi).
pub const FLAG_VOLATILE: u8 = 0x1;

/// Signature value: operand class unconstrained (`SIGNATURE_TABLE`).
pub const ANY: u8 = 0;
/// Signature value: general-purpose register (`SIGNATURE_TABLE`).
pub const GP: u8 = 1;
/// Signature value: floating-point register (`SIGNATURE_TABLE`).
pub const FP: u8 = 2;
/// Signature value: vector register (`SIGNATURE_TABLE`).
pub const VEC: u8 = 3;
/// Signature value: immediate or label (`SIGNATURE_TABLE`).
pub const IMM: u8 = 4;

/// Per-opcode instruction information.
#[derive(Clone, Copy, Debug)]
pub struct InstInfo {{
    /// Index into [`RW_PATTERN_TABLE`].
    pub rw_info_index: u8,
    /// Index into [`SIGNATURE_TABLE`].
    pub signature_index: u8,
    /// `MEM_*` access kind.
    pub mem_access: u8,
    /// Access width in bytes (0 = none or not instruction-fixed).
    pub mem_width: u8,
    /// Index into [`IMPLICIT_REG_TABLE`].
    pub implicit_index: u8,
    /// `FLAG_*` bits.
    pub flags: u8,
    /// Implicit CSR flag reads (`CpuRwFlags::RISCV_*` bits).
    pub read_flags: u32,
    /// Implicit CSR flag writes (`CpuRwFlags::RISCV_*` bits).
    pub write_flags: u32,
}}

/// Implicit fixed-register effects. Bits 0..=31 name GP registers x0..x31; bit 32
/// names the vector mask register v0.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ImplicitRegEffects {{
    /// Mask of implicitly read fixed registers.
    pub read: u64,
    /// Mask of implicitly written fixed registers.
    pub write: u64,
}}

/// Deduplicated operand read/write patterns (`OpRwFlags` values per position).
#[rustfmt::skip]
pub static RW_PATTERN_TABLE: [[u32; 6]; {len(patterns)}] = [
"""
    for p in patterns:
        out += f"    [{', '.join(p)}],\n"
    out += "];\n\n"

    out += f"""/// Deduplicated operand-class signatures (`ANY`/`GP`/`FP`/`VEC`/`IMM` per position).
#[rustfmt::skip]
pub static SIGNATURE_TABLE: [[u8; 6]; {len(signatures)}] = [
"""
    for s in signatures:
        out += f"    [{', '.join(s)}],\n"
    out += "];\n\n"

    out += f"""/// Deduplicated implicit fixed-register effects (index 0 = none).
pub static IMPLICIT_REG_TABLE: [ImplicitRegEffects; {len(implicits)}] = [
"""
    for read_mask, write_mask in implicits:
        out += f"    ImplicitRegEffects {{ read: {hex(read_mask)}, write: {hex(write_mask)} }},\n"
    out += "];\n\n"

    out += f"""/// Per-opcode effects, indexed by `Opcode as usize`.
#[rustfmt::skip]
pub static INST_INFO_TABLE: [InstInfo; {len(instr_dict)}] = [
"""
    mem_const = {"LOAD": "MEM_LOAD", "STORE": "MEM_STORE", "RMW": "MEM_READ_MODIFY_WRITE"}
    for i in instr_dict:
        e = effects[i]
        mem_access, mem_width = e["mem"] if e["mem"] is not None else ("NONE", 0)
        mem_access = mem_const.get(mem_access, "MEM_NONE")
        flags = "FLAG_VOLATILE" if e["volatile"] else "0"
        read_flags = " | ".join(
            f"CpuRwFlags::RISCV_{f}.bits()" for f in sorted(e["read_flags"])
        ) or "0"
        write_flags = " | ".join(
            f"CpuRwFlags::RISCV_{f}.bits()" for f in sorted(e["write_flags"])
        ) or "0"
        out += (
            f"    InstInfo {{ rw_info_index: {pattern_index[pattern_key(e)]}, "
            f"signature_index: {signature_index[signature_key(e)]}, "
            f"mem_access: {mem_access}, mem_width: {mem_width}, "
            f"implicit_index: {implicit_index[e['implicit']]}, flags: {flags}, "
            f"read_flags: {read_flags}, write_flags: {write_flags} }}, // {doc_key(i)}\n"
        )
    out += "];\n\n"

    out += """impl Opcode {
    /// Returns the effects database entry for this opcode.
    pub fn inst_info(self) -> &'static InstInfo {
        &INST_INFO_TABLE[self as usize]
    }

    /// Returns the implicit fixed-register effects of this opcode.
    pub fn implicit_reg_effects(self) -> &'static ImplicitRegEffects {
        &IMPLICIT_REG_TABLE[self.inst_info().implicit_index as usize]
    }
}
"""
    return out


def write_opcodes(instr_dict, docs):
    """Writes src/riscv/opcodes.rs, preserving the hand-maintained immediate
    section above the generation marker byte-identical.
    """
    path = os.path.join(SRC_RISCV, "opcodes.rs")
    with open(path) as fp:
        current = fp.read()
    marker = current.index(GENERATED_MARKER)
    head = current[:marker]
    with open(path, "w") as fp:
        fp.write(head + make_opcodes(instr_dict, docs))
    logging.info(f"wrote {path}")


def main():
    extensions = [a for a in sys.argv[1:] if not a.startswith("-")]
    if not extensions:
        extensions = ["rv*"]

    docs = load_inst_docs()
    logging.info(f"loaded {len(docs)} unified-db docs")

    instr_dict = create_inst_dict(extensions, include_pseudo=True)
    instr_dict = collections.OrderedDict(sorted(instr_dict.items()))
    logging.info(f"{len(instr_dict)} instructions after exclusions {sorted(EXCLUDED_EXTENSIONS)}")

    arm_orders = parse_emit_arm_orders(os.path.join(SRC_RISCV, "assembler.rs"))
    effects, stats = derive_effects(instr_dict, arm_orders)

    write_opcodes(instr_dict, docs)

    emitter_path = os.path.join(SRC_RISCV, "emitter.rs")
    with open(emitter_path, "w") as fp:
        fp.write(make_encoders(instr_dict, docs))
    logging.info(f"wrote {emitter_path}")

    instdb_path = os.path.join(SRC_RISCV, "instdb.rs")
    with open(instdb_path, "w") as fp:
        fp.write(make_instdb(instr_dict, effects, stats))
    logging.info(f"wrote {instdb_path}")

    logging.info(f"effects derivation stats: {dict(stats)}")


if __name__ == "__main__":
    main()
