//! Differential-test corpus generator for the x86 backend.
//!
//! This binary is NOT part of the asmkit repository. It is copied into the
//! extracted *baseline* tree (target/difftest-baseline/src/bin/) by
//! meta/difftest/materialize.sh and built against the pre-rewrite x86 encoder.
//!
//! It drives the baseline's dynamic instruction API (`Instruction::from_mnem`
//! + `emit`) over operand grids derived from `corpus_recipes.rs` (generated by
//! meta/difftest/extract_recipes.py from the baseline's _DYN.rs), and writes a
//! binary corpus of (mnemonic, operands, options, expected bytes) records.
//! See meta/difftest/FORMAT.md for the record format.

use std::collections::{BTreeMap, HashSet};
use std::io::Write;
use std::panic::AssertUnwindSafe;

use asmkit::core::buffer::CodeBuffer;
use asmkit::core::operand::{Imm, Label, Operand, OperandCast, OperandSignature, imm};
use asmkit::x86::assembler::Assembler;
use asmkit::x86::features::dyn_emit::Instruction;
use asmkit::x86::opcodes;
use asmkit::x86::operands::{Broadcast, Mem, Reg};

include!("corpus_recipes.rs");

// ============================================================================
// RegType discriminants (mirror src/core/operand.rs TryFrom<u32>).
// ============================================================================
const RT_NONE: u8 = 0;
const RT_PC: u8 = 3;
const RT_GP8LO: u8 = 4;
const RT_GP8HI: u8 = 5;
const RT_GP16: u8 = 6;
const RT_GP32: u8 = 7;
const RT_GP64: u8 = 8;
const RT_VEC128: u8 = 13;
const RT_VEC256: u8 = 14;
const RT_VEC512: u8 = 15;
const RT_MASK: u8 = 17;
const RT_MM: u8 = 18; // RegType::Extra == X86Mm
const RT_SREG: u8 = 19;
const RT_CREG: u8 = 20;
const RT_DREG: u8 = 21;
const RT_ST: u8 = 22;
const RT_TMM: u8 = 24;

// Operand kind tags in the record.
const OK_REG: u8 = 1;
const OK_MEM: u8 = 2;
const OK_IMM: u8 = 3;
const OK_LABEL: u8 = 4;

// Label layout tags in the record.
const LL_SELF: u8 = 0; // label bound at the instruction's own offset
const LL_FAR_BACK: u8 = 1; // label bound at block start, 200 pad bytes before the instruction
const LL_FAR_FWD: u8 = 2; // label bound after instruction + 200 pad bytes
const LABEL_PAD: usize = 200;

const MAGIC: &[u8; 8] = b"AKDFCOR1";

// ============================================================================
// Options (prefixes / EVEX extras) applied before emit.
// ============================================================================
#[derive(Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord)]
struct Opts {
    lock: bool,
    rep: bool,
    repnz: bool,
    seg: u8,       // 0 = none, 1..=6 = es,cs,ss,ds,fs,gs
    er: u8,        // 0 = none, 1 = sae, 2 = rn, 3 = rd, 4 = ru, 5 = rz
    k: Option<u8>, // EVEX mask register id
}

// ============================================================================
// Stats
// ============================================================================
#[derive(Default)]
struct Stats {
    attempts: u64,
    from_mnem_ok: u64,
    emit_ok: u64,
    panics: u64,
    records: u64,
    bytes: u64,
    verify_dropped: u64,
    sym_forms_skipped: u64,
    mixed_label_skipped: u64,
    mnems_covered: HashSet<&'static str>,
    drop_reasons: BTreeMap<(String, String), u64>,
}

// ============================================================================
// Record: one corpus entry.
// ============================================================================
struct OpRec {
    kind: u8,
    // reg
    rt: u8,
    id: u8,
    // mem
    base_rt: u8,
    base_id: u8,
    index_rt: u8,
    index_id: u8,
    scale: u8,
    size: u8,
    addr_type: u8,
    broadcast: u8,
    disp: i64,
}

impl OpRec {
    fn none() -> Self {
        Self {
            kind: 0,
            rt: 0,
            id: 0,
            base_rt: 0,
            base_id: 0,
            index_rt: 0,
            index_id: 0,
            scale: 0,
            size: 0,
            addr_type: 0,
            broadcast: 0,
            disp: 0,
        }
    }

    /// Read back an operand exactly as the encoder consumed it.
    fn from_operand(op: &Operand) -> Self {
        let mut r = Self::none();
        if op.is_reg() {
            let reg = op.as_::<Reg>();
            r.kind = OK_REG;
            r.rt = reg.typ() as u32 as u8;
            r.id = reg.id() as u8;
        } else if op.is_mem() {
            let m = op.as_::<Mem>();
            r.kind = OK_MEM;
            r.base_rt = m.base_type() as u32 as u8;
            r.base_id = m.base_id() as u8;
            r.index_rt = m.index_type() as u32 as u8;
            r.index_id = m.index_id() as u8;
            r.scale = m.shift() as u8;
            r.size = m.size() as u8;
            r.addr_type = m.addr_type() as u32 as u8;
            r.broadcast = m.get_broadcast() as u32 as u8;
            r.disp = m.offset();
        } else if op.is_imm() {
            r.kind = OK_IMM;
            r.disp = op.as_::<Imm>().value();
        } else if op.is_label() {
            r.kind = OK_LABEL;
        }
        r
    }

    fn write(&self, w: &mut Vec<u8>) {
        w.push(self.kind);
        match self.kind {
            OK_REG => {
                w.push(self.rt);
                w.push(self.id);
            }
            OK_MEM => {
                w.push(self.base_rt);
                w.push(self.base_id);
                w.push(self.index_rt);
                w.push(self.index_id);
                w.push(self.scale);
                w.push(self.size);
                w.push(self.addr_type);
                w.push(self.broadcast);
                w.extend_from_slice(&self.disp.to_le_bytes());
            }
            OK_IMM => {
                w.extend_from_slice(&self.disp.to_le_bytes());
            }
            _ => {}
        }
    }
}

struct Record {
    mnem: String,
    opcode: i64,
    opts: Opts,
    ops: Vec<OpRec>,
    label_layout: u8,       // 0xFF = no label
    label_bind_offset: i32, // -1 = no label
    instr_offset: u32,
    instr_len: u32,
    block: Vec<u8>,
}

impl Record {
    fn write(&self, w: &mut dyn Write) -> std::io::Result<()> {
        let mut p = Vec::with_capacity(64 + self.block.len());
        p.extend_from_slice(&(self.mnem.len() as u16).to_le_bytes());
        p.extend_from_slice(self.mnem.as_bytes());
        p.extend_from_slice(&self.opcode.to_le_bytes());
        p.push(self.ops.len() as u8);
        p.push(
            (self.opts.lock as u8) | ((self.opts.rep as u8) << 1) | ((self.opts.repnz as u8) << 2),
        );
        p.push(self.opts.seg | (self.opts.er << 3) | ((self.opts.k.is_some() as u8) << 6));
        p.push(self.opts.k.unwrap_or(0));
        p.push(self.label_layout);
        p.extend_from_slice(&self.label_bind_offset.to_le_bytes());
        p.extend_from_slice(&self.instr_offset.to_le_bytes());
        p.extend_from_slice(&self.instr_len.to_le_bytes());
        for op in &self.ops {
            op.write(&mut p);
        }
        p.extend_from_slice(&(self.block.len() as u32).to_le_bytes());
        p.extend_from_slice(&self.block);
        w.write_all(&(p.len() as u32).to_le_bytes())?;
        w.write_all(&p)
    }
}

// ============================================================================
// Emission
// ============================================================================
fn apply_opts(asm: &mut Assembler, opts: &Opts) {
    if opts.lock {
        asm.lock();
    }
    if opts.rep {
        asm.rep();
    }
    if opts.repnz {
        asm.repnz();
    }
    if opts.seg != 0 {
        asm.seg(asmkit::x86::operands::regs::sreg(opts.seg as u32));
    }
    match opts.er {
        1 => {
            asm.sae();
        }
        2 => {
            asm.rn_sae();
        }
        3 => {
            asm.rd_sae();
        }
        4 => {
            asm.ru_sae();
        }
        5 => {
            asm.rz_sae();
        }
        _ => {}
    }
    if let Some(k) = opts.k {
        asm.k(asmkit::x86::operands::regs::k(k as u32));
    }
}

struct EmitOut {
    block: Vec<u8>,
    instr_offset: u32,
    instr_len: u32,
    label_bind_offset: i32,
}

/// Emit `instr` with `opts` into a fresh buffer. `label_layout` applies when
/// one of the operands is a label (the operand value is created here).
/// Returns None when the encoder reports an error or panics.
fn emit_record(
    instr_ops: &[Operand],
    opcode: i64,
    opts: &Opts,
    label_layout: u8,
    panics: &mut u64,
) -> Option<EmitOut> {
    let mut buf = CodeBuffer::new();
    let mut asm = Assembler::new(&mut buf);

    let mut ops: Vec<Operand> = instr_ops.to_vec();
    let mut label = None;
    if label_layout != 0xFF {
        let l = asm.get_label();
        label = Some(l);
        for o in ops.iter_mut() {
            if o.is_label() {
                *o = *l.as_operand();
            }
        }
        if label_layout != LL_FAR_FWD {
            asm.bind_label(l);
            if label_layout == LL_FAR_BACK {
                for _ in 0..LABEL_PAD {
                    asm.buffer.put1(0x90);
                }
            }
        }
    }

    let instr_offset = asm.buffer.cur_offset();
    apply_opts(&mut asm, opts);

    let instr = Instruction {
        opcode,
        op0: ops.first().copied().unwrap_or_else(Operand::new),
        op1: ops.get(1).copied().unwrap_or_else(Operand::new),
        op2: ops.get(2).copied().unwrap_or_else(Operand::new),
        op3: ops.get(3).copied().unwrap_or_else(Operand::new),
    };

    let ok = std::panic::catch_unwind(AssertUnwindSafe(|| {
        instr.emit(&mut asm);
    }))
    .is_ok();
    if !ok {
        *panics += 1;
        return None;
    }
    if asm.last_error().is_some() {
        return None;
    }
    let instr_len = asm.buffer.cur_offset() - instr_offset;
    if instr_len == 0 {
        return None;
    }

    let mut label_bind_offset = -1i32;
    if let Some(l) = label {
        if label_layout == LL_FAR_FWD {
            for _ in 0..LABEL_PAD {
                asm.buffer.put1(0x90);
            }
            asm.bind_label(l);
        }
        // Apply pending fixups (all labels are bound at this point, so no
        // veneers can be emitted).
        asm.buffer.emit_island(0);
        if asm.last_error().is_some() {
            return None;
        }
        label_bind_offset = asm.label_offset(l) as i32;
    }

    Some(EmitOut {
        block: asm.buffer.data().to_vec(),
        instr_offset,
        instr_len,
        label_bind_offset,
    })
}

// ============================================================================
// Verification with iced-x86.
// ============================================================================
mod verify {
    use super::*;
    use iced_x86::{Decoder, DecoderOptions, Mnemonic, OpKind, Register};

    pub struct Verifier;

    const GP8LO: [Register; 16] = [
        Register::AL,
        Register::CL,
        Register::DL,
        Register::BL,
        Register::SPL,
        Register::BPL,
        Register::SIL,
        Register::DIL,
        Register::R8L,
        Register::R9L,
        Register::R10L,
        Register::R11L,
        Register::R12L,
        Register::R13L,
        Register::R14L,
        Register::R15L,
    ];
    const GP8HI: [Register; 4] = [Register::AH, Register::CH, Register::DH, Register::BH];
    const GP16: [Register; 16] = [
        Register::AX,
        Register::CX,
        Register::DX,
        Register::BX,
        Register::SP,
        Register::BP,
        Register::SI,
        Register::DI,
        Register::R8W,
        Register::R9W,
        Register::R10W,
        Register::R11W,
        Register::R12W,
        Register::R13W,
        Register::R14W,
        Register::R15W,
    ];
    const GP32: [Register; 16] = [
        Register::EAX,
        Register::ECX,
        Register::EDX,
        Register::EBX,
        Register::ESP,
        Register::EBP,
        Register::ESI,
        Register::EDI,
        Register::R8D,
        Register::R9D,
        Register::R10D,
        Register::R11D,
        Register::R12D,
        Register::R13D,
        Register::R14D,
        Register::R15D,
    ];
    const GP64: [Register; 16] = [
        Register::RAX,
        Register::RCX,
        Register::RDX,
        Register::RBX,
        Register::RSP,
        Register::RBP,
        Register::RSI,
        Register::RDI,
        Register::R8,
        Register::R9,
        Register::R10,
        Register::R11,
        Register::R12,
        Register::R13,
        Register::R14,
        Register::R15,
    ];
    const XMM: [Register; 32] = [
        Register::XMM0,
        Register::XMM1,
        Register::XMM2,
        Register::XMM3,
        Register::XMM4,
        Register::XMM5,
        Register::XMM6,
        Register::XMM7,
        Register::XMM8,
        Register::XMM9,
        Register::XMM10,
        Register::XMM11,
        Register::XMM12,
        Register::XMM13,
        Register::XMM14,
        Register::XMM15,
        Register::XMM16,
        Register::XMM17,
        Register::XMM18,
        Register::XMM19,
        Register::XMM20,
        Register::XMM21,
        Register::XMM22,
        Register::XMM23,
        Register::XMM24,
        Register::XMM25,
        Register::XMM26,
        Register::XMM27,
        Register::XMM28,
        Register::XMM29,
        Register::XMM30,
        Register::XMM31,
    ];
    const YMM: [Register; 32] = [
        Register::YMM0,
        Register::YMM1,
        Register::YMM2,
        Register::YMM3,
        Register::YMM4,
        Register::YMM5,
        Register::YMM6,
        Register::YMM7,
        Register::YMM8,
        Register::YMM9,
        Register::YMM10,
        Register::YMM11,
        Register::YMM12,
        Register::YMM13,
        Register::YMM14,
        Register::YMM15,
        Register::YMM16,
        Register::YMM17,
        Register::YMM18,
        Register::YMM19,
        Register::YMM20,
        Register::YMM21,
        Register::YMM22,
        Register::YMM23,
        Register::YMM24,
        Register::YMM25,
        Register::YMM26,
        Register::YMM27,
        Register::YMM28,
        Register::YMM29,
        Register::YMM30,
        Register::YMM31,
    ];
    const ZMM: [Register; 32] = [
        Register::ZMM0,
        Register::ZMM1,
        Register::ZMM2,
        Register::ZMM3,
        Register::ZMM4,
        Register::ZMM5,
        Register::ZMM6,
        Register::ZMM7,
        Register::ZMM8,
        Register::ZMM9,
        Register::ZMM10,
        Register::ZMM11,
        Register::ZMM12,
        Register::ZMM13,
        Register::ZMM14,
        Register::ZMM15,
        Register::ZMM16,
        Register::ZMM17,
        Register::ZMM18,
        Register::ZMM19,
        Register::ZMM20,
        Register::ZMM21,
        Register::ZMM22,
        Register::ZMM23,
        Register::ZMM24,
        Register::ZMM25,
        Register::ZMM26,
        Register::ZMM27,
        Register::ZMM28,
        Register::ZMM29,
        Register::ZMM30,
        Register::ZMM31,
    ];
    const KREG: [Register; 8] = [
        Register::K0,
        Register::K1,
        Register::K2,
        Register::K3,
        Register::K4,
        Register::K5,
        Register::K6,
        Register::K7,
    ];
    const MMREG: [Register; 8] = [
        Register::MM0,
        Register::MM1,
        Register::MM2,
        Register::MM3,
        Register::MM4,
        Register::MM5,
        Register::MM6,
        Register::MM7,
    ];
    const STREG: [Register; 8] = [
        Register::ST0,
        Register::ST1,
        Register::ST2,
        Register::ST3,
        Register::ST4,
        Register::ST5,
        Register::ST6,
        Register::ST7,
    ];
    const SREG: [Register; 7] = [
        Register::None,
        Register::ES,
        Register::CS,
        Register::SS,
        Register::DS,
        Register::FS,
        Register::GS,
    ];
    const CREG: [Register; 16] = [
        Register::CR0,
        Register::CR1,
        Register::CR2,
        Register::CR3,
        Register::CR4,
        Register::CR5,
        Register::CR6,
        Register::CR7,
        Register::CR8,
        Register::CR9,
        Register::CR10,
        Register::CR11,
        Register::CR12,
        Register::CR13,
        Register::CR14,
        Register::CR15,
    ];
    const DREG: [Register; 16] = [
        Register::DR0,
        Register::DR1,
        Register::DR2,
        Register::DR3,
        Register::DR4,
        Register::DR5,
        Register::DR6,
        Register::DR7,
        Register::DR8,
        Register::DR9,
        Register::DR10,
        Register::DR11,
        Register::DR12,
        Register::DR13,
        Register::DR14,
        Register::DR15,
    ];
    const TMM: [Register; 8] = [
        Register::TMM0,
        Register::TMM1,
        Register::TMM2,
        Register::TMM3,
        Register::TMM4,
        Register::TMM5,
        Register::TMM6,
        Register::TMM7,
    ];

    fn reg_of(rt: u8, id: u8) -> Option<Register> {
        let i = id as usize;
        Some(match rt {
            RT_GP8LO => *GP8LO.get(i)?,
            RT_GP8HI => *GP8HI.get(i)?,
            RT_GP16 => *GP16.get(i)?,
            RT_GP32 => *GP32.get(i)?,
            RT_GP64 => *GP64.get(i)?,
            RT_VEC128 => *XMM.get(i)?,
            RT_VEC256 => *YMM.get(i)?,
            RT_VEC512 => *ZMM.get(i)?,
            RT_MASK => *KREG.get(i)?,
            RT_MM => *MMREG.get(i)?,
            RT_ST => *STREG.get(i)?,
            RT_SREG => *SREG.get(i)?,
            RT_CREG => *CREG.get(i)?,
            RT_DREG => *DREG.get(i)?,
            RT_TMM => *TMM.get(i)?,
            RT_PC => Register::RIP,
            _ => return None,
        })
    }

    /// Mnemonics whose iced-decoded name legitimately differs from the
    /// recorded (asmkit) name. Values are the accepted iced names.
    const MNEM_ALIASES: &[(&str, &[&str])] = &[
        ("movsx", &["movsxd"]),
        ("jcxz", &["jrcxz"]),
        ("sal", &["shl"]),
        ("jc", &["jb"]),
        ("jnc", &["jae"]),
        ("jz", &["je"]),
        ("jnz", &["jne"]),
        ("jcc", &["jo"]),
        ("cmovc", &["cmovb"]),
        ("cmovnc", &["cmovae"]),
        ("cmovz", &["cmove"]),
        ("cmovnz", &["cmovne"]),
        ("cmovcc", &["cmovo"]),
        ("setc", &["setb"]),
        ("setnc", &["setae"]),
        ("setz", &["sete"]),
        ("setnz", &["setne"]),
        ("setcc", &["seto"]),
        ("cmpxchgd", &["cmpxchg8b"]),
        ("cmpxchg8bm", &["cmpxchg8b"]),
        ("cmpxchg16bm", &["cmpxchg16b"]),
        ("fsave", &["fnsave"]),
        ("fstcw", &["fnstcw"]),
        ("fstenv", &["fnstenv"]),
        ("fstsw", &["fnstsw"]),
        ("incssp", &["incsspq"]),
        ("rdssp", &["rdsspq"]),
        ("fwait", &["wait"]),
        ("fclex", &["fnclex"]),
        ("finit", &["fninit"]),
        ("c_ex", &["cbw"]),
        ("c_sep", &["cwd"]),
        ("wrss", &["wrssq", "wrssd"]),
        ("wruss", &["wrussq", "wrussd"]),
        ("loopz", &["loope"]),
        ("loopnz", &["loopne"]),
        ("sse_cvtsd2si", &["cvtsd2si"]),
        ("sse_cvtss2si", &["cvtss2si"]),
        ("sse_cvttsd2si", &["cvttsd2si"]),
        ("sse_cvttss2si", &["cvttss2si"]),
        ("movs", &["movsb", "movsw", "movsd", "movsq"]),
        ("movs8", &["movsb"]),
        ("movs16", &["movsw"]),
        ("movs32", &["movsd"]),
        ("movs64", &["movsq"]),
        ("stos", &["stosb", "stosw", "stosd", "stosq"]),
        ("stos8", &["stosb"]),
        ("stos16", &["stosw"]),
        ("stos32", &["stosd"]),
        ("stos64", &["stosq"]),
        ("lods", &["lodsb", "lodsw", "lodsd", "lodsq"]),
        ("lods8", &["lodsb"]),
        ("lods16", &["lodsw"]),
        ("lods32", &["lodsd"]),
        ("lods64", &["lodsq"]),
        ("cmps", &["cmpsb", "cmpsw", "cmpsd", "cmpsq"]),
        ("cmps8", &["cmpsb"]),
        ("cmps16", &["cmpsw"]),
        ("cmps32", &["cmpsd"]),
        ("cmps64", &["cmpsq"]),
        ("scas", &["scasb", "scasw", "scasd", "scasq"]),
        ("scas8", &["scasb"]),
        ("scas16", &["scasw"]),
        ("scas32", &["scasd"]),
        ("scas64", &["scasq"]),
        ("ins", &["insb", "insw", "insd"]),
        ("ins8", &["insb"]),
        ("ins16", &["insw"]),
        ("ins32", &["insd"]),
        ("outs", &["outsb", "outsw", "outsd"]),
        ("outs8", &["outsb"]),
        ("outs16", &["outsw"]),
        ("outs32", &["outsd"]),
        ("retf", &["retfq"]),
        ("jmpf", &["jmp"]),
        ("callf", &["call"]),
        (
            "cmpccxadd",
            &[
                "cmpoxadd",
                "cmpnoxadd",
                "cmpbadd",
                "cmpaeadd",
                "cmpzadd",
                "cmpnzadd",
                "cmpbeadd",
                "cmpaadd",
                "cmpsadd",
                "cmpnsadd",
                "cmppadd",
                "cmpnpadd",
                "cmpladd",
                "cmpgeadd",
                "cmpleadd",
                "cmpgadd",
            ],
        ),
        (
            "cmptccxadd",
            &[
                "cmpoxadd",
                "cmpnoxadd",
                "cmpbadd",
                "cmpaeadd",
                "cmpzadd",
                "cmpnzadd",
                "cmpbeadd",
                "cmpaadd",
                "cmpsadd",
                "cmpnsadd",
                "cmppadd",
                "cmpnpadd",
                "cmpladd",
                "cmpgeadd",
                "cmpleadd",
                "cmpgadd",
            ],
        ),
        ("xchg", &["nop"]),
        ("int3", &["int3"]),
        ("cbw", &["cbw"]),
    ];

    fn mnem_matches(recorded: &str, iced: Mnemonic) -> bool {
        let iced_name = format!("{iced:?}").to_ascii_lowercase();
        // asmkit prefixes legacy SSE/MMX instruction names with isa tags
        // ("sse_blendvpd") and tags operand direction/source with infixes
        // ("vmovq_g2x", "mov_s2g"); iced uses the plain names.
        let mut candidates = vec![recorded];
        for pfx in ["sse4_", "ssse3_", "sse3_", "sse2_", "sse_", "mmx_"] {
            if let Some(stripped) = recorded.strip_prefix(pfx) {
                candidates.push(stripped);
            }
        }
        for infix in [
            "_g2x", "_x2g", "_g2m", "_m2g", "_g2s", "_s2g", "_g2cr", "_cr2g", "_g2dr", "_dr2g",
        ] {
            for c in candidates.clone() {
                if let Some((base, _)) = c.split_once(infix) {
                    candidates.push(base);
                }
            }
        }
        if candidates.iter().any(|c| *c == iced_name) {
            return true;
        }
        for (rec, allowed) in MNEM_ALIASES {
            if *rec == recorded && allowed.contains(&iced_name.as_str()) {
                return true;
            }
        }
        false
    }

    fn imm_mask(kind: OpKind) -> Option<u64> {
        Some(match kind {
            OpKind::Immediate8
            | OpKind::Immediate8_2nd
            | OpKind::Immediate8to16
            | OpKind::Immediate8to32
            | OpKind::Immediate8to64 => 0xff,
            OpKind::Immediate16 => 0xffff,
            OpKind::Immediate32 | OpKind::Immediate32to64 => 0xffff_ffff,
            OpKind::Immediate64 => u64::MAX,
            _ => return None,
        })
    }

    /// Verify one record; returns Ok(()) or Err(reason).
    pub fn check(rec: &Record) -> Result<(), String> {
        let start = rec.instr_offset as usize;
        let end = start + rec.instr_len as usize;
        if end > rec.block.len() {
            return Err("instr out of block bounds".into());
        }
        let bytes = &rec.block[start..end];
        let mut dec = Decoder::with_ip(64, bytes, rec.instr_offset as u64, DecoderOptions::NONE);
        let instr = dec.decode();
        if instr.is_invalid() || dec.position() != rec.instr_len as usize {
            return Err("decode-failed".into());
        }
        // Strip the _mask/_maskz/_er/_sae suffixes and the _gp infix for the
        // comparison (they are asmkit operand-source/EVEX options, not part
        // of the decoded mnemonic). Suffix-anchored: "sse_maskmovdqu" must
        // survive intact. Tags can combine ("vcmppd_mask_sae"), so strip
        // repeatedly.
        let mut base_mnem = rec.mnem.as_str();
        loop {
            let mut stripped = false;
            for sfx in ["_maskz", "_mask", "_er", "_sae"] {
                if let Some(b) = base_mnem.strip_suffix(sfx) {
                    base_mnem = b;
                    stripped = true;
                }
            }
            if !stripped {
                break;
            }
        }
        if let Some(b) = base_mnem.strip_suffix("_gp") {
            base_mnem = b;
        }
        let base_mnem = base_mnem.to_string();
        if !mnem_matches(&base_mnem, instr.mnemonic()) {
            return Err(format!("mnem:{:?}", instr.mnemonic()).to_lowercase());
        }
        // xchg r,r with equal ids is encoded as 0x90 (nop); operand compare
        // does not apply.
        if base_mnem == "xchg" && instr.mnemonic() == Mnemonic::Nop {
            return Ok(());
        }
        let n_ops = rec.ops.len();
        if (instr.op_count() as usize) < n_ops {
            // Some instructions have implicit fixed-register operands that
            // iced does not list (e.g. sha256rnds2's implicit xmm0). Allow
            // trailing recorded register operands with id 0; they do not
            // appear in the encoding. Any other shortfall is a mismatch.
            let trailing_ok = rec.ops[instr.op_count() as usize..]
                .iter()
                .all(|op| op.kind == OK_REG && op.id == 0);
            if !trailing_ok {
                return Err(format!("opcount:{}<{}", instr.op_count(), n_ops));
            }
        }
        // maskmovq/maskmovdqu/vmaskmovdqu: iced lists the implicit
        // ds:[rdi]/[edi] memory operand first, while the record only
        // contains the explicit register operands.
        let iced_off = if (base_mnem.ends_with("maskmovdqu") || base_mnem.ends_with("maskmovq"))
            && instr.op_count() as usize == n_ops + 1
            && matches!(
                instr.op_kind(0),
                OpKind::Memory | OpKind::MemorySegRDI | OpKind::MemorySegEDI | OpKind::MemorySegRSI
            ) {
            1u32
        } else {
            0
        };
        for (i, op) in rec.ops.iter().enumerate() {
            if i >= instr.op_count() as usize {
                // Trailing implicit operands already validated above.
                break;
            }
            let io = i as u32 + iced_off;
            let kind = instr.op_kind(io);
            match op.kind {
                OK_REG => {
                    if kind != OpKind::Register {
                        return Err(format!("op{i}:not-reg"));
                    }
                    if (base_mnem == "lar" || base_mnem == "lsl") && i == 1 {
                        // iced models the r/m16 source of lar/lsl as a 32-bit
                        // register; the encoding only carries the id.
                        let iced_id = [GP16.as_slice(), GP32.as_slice(), GP64.as_slice()]
                            .iter()
                            .find_map(|t| t.iter().position(|r| *r == instr.op_register(io)));
                        match iced_id {
                            Some(id) if id == op.id as usize => {}
                            _ => return Err(format!("op{i}:reg-mismatch")),
                        }
                        continue;
                    }
                    match reg_of(op.rt, op.id) {
                        Some(r) if r == instr.op_register(io) => {}
                        _ => return Err(format!("op{i}:reg-mismatch")),
                    }
                }
                OK_IMM => {
                    match imm_mask(kind) {
                        Some(mask) => {
                            let got = instr.immediate(io) & mask;
                            let want = (op.disp as u64) & mask;
                            if got != want {
                                return Err(format!("op{i}:imm:{got:#x}!={want:#x}"));
                            }
                        }
                        None => {
                            if matches!(
                                kind,
                                OpKind::NearBranch16 | OpKind::NearBranch32 | OpKind::NearBranch64
                            ) {
                                // jmp/call/jcc with an immediate: the encoder
                                // stores the raw displacement.
                                let t = instr.near_branch_target() as i64;
                                let want = rec.instr_offset as i64 + rec.instr_len as i64 + op.disp;
                                if t != want {
                                    return Err(format!("op{i}:brimm:{t:#x}!={want:#x}"));
                                }
                            } else if kind == OpKind::Register {
                                // Some instructions encode a register into the
                                // immediate (e.g. vblendvpd). The old dyn API
                                // passes an xmm operand for those.
                                match reg_of(RT_VEC128, (op.disp >> 4) as u8) {
                                    Some(r) if r == instr.op_register(io) => {}
                                    _ => return Err(format!("op{i}:immreg-mismatch")),
                                }
                            } else {
                                return Err(format!("op{i}:not-imm"));
                            }
                        }
                    }
                }
                OK_MEM => {
                    if kind != OpKind::Memory {
                        return Err(format!("op{i}:not-mem"));
                    }
                    let want_base = if op.base_rt == RT_NONE {
                        Register::None
                    } else {
                        match reg_of(op.base_rt, op.base_id) {
                            Some(r) => r,
                            None => return Err(format!("op{i}:base-unmapped")),
                        }
                    };
                    if instr.memory_base() != want_base {
                        return Err(format!("op{i}:mem-base"));
                    }
                    let want_index = if op.index_rt == RT_NONE {
                        Register::None
                    } else {
                        match reg_of(op.index_rt, op.index_id) {
                            Some(r) => r,
                            None => return Err(format!("op{i}:index-unmapped")),
                        }
                    };
                    if instr.memory_index() != want_index {
                        return Err(format!("op{i}:mem-index"));
                    }
                    if instr.memory_index_scale() != (1u32 << op.scale) {
                        return Err(format!("op{i}:mem-scale"));
                    }
                    if instr.memory_displacement64() != (op.disp as u64) {
                        return Err(format!(
                            "op{i}:mem-disp:{:#x}!={:#x}",
                            instr.memory_displacement64(),
                            op.disp
                        ));
                    }
                    if instr.is_broadcast() != (op.broadcast != 0) {
                        return Err(format!("op{i}:mem-bcst"));
                    }
                }
                OK_LABEL => {
                    // Checked below via near_branch_target.
                    if !matches!(
                        kind,
                        OpKind::NearBranch16 | OpKind::NearBranch32 | OpKind::NearBranch64
                    ) {
                        return Err(format!("op{i}:not-branch"));
                    }
                }
                _ => {}
            }
        }
        if rec.label_bind_offset >= 0 {
            let target = instr.near_branch_target();
            if target != rec.label_bind_offset as u64 {
                return Err(format!(
                    "branch-target:{target:#x}!={:#x}",
                    rec.label_bind_offset
                ));
            }
        }
        Ok(())
    }
}

// ============================================================================
// Operand template pools.
// ============================================================================
fn reg_op(rt: u8, id: u8) -> Operand {
    // NOTE: do not use Reg::from_type_and_id here — the baseline's x86
    // ArchTraits::regs_signature table is misindexed by one (it lacks the
    // SymTag slot), so it maps several RegTypes to wrong signatures (e.g.
    // Gp64 -> None, Vec128 -> Zmm). The typed constructors carry correct
    // signatures.
    use asmkit::x86::operands::regs::*;
    let i = id as u32;
    match rt {
        RT_GP8LO => *gpb_lo(i).as_operand(),
        RT_GP8HI => *gpb_hi(i).as_operand(),
        RT_GP16 => *gpw(i).as_operand(),
        RT_GP32 => *gpd(i).as_operand(),
        RT_GP64 => *gpq(i).as_operand(),
        RT_VEC128 => *xmm(i).as_operand(),
        RT_VEC256 => *ymm(i).as_operand(),
        RT_VEC512 => *zmm(i).as_operand(),
        RT_MASK => *k(i).as_operand(),
        RT_MM => *mm(i).as_operand(),
        RT_ST => *st(i).as_operand(),
        RT_TMM => *tmm(i).as_operand(),
        RT_SREG => *sreg(i).as_operand(),
        RT_CREG => *cr(i).as_operand(),
        RT_DREG => *dr(i).as_operand(),
        RT_PC => *rip().as_operand(),
        _ => panic!("bad reg type {rt}"),
    }
}

#[derive(Clone)]
struct MemT {
    base_rt: u8,
    base_id: u8,
    index_rt: u8,
    index_id: u8,
    scale: u8,
    disp: i64,
    size: u8,
    addr_type: u8, // 0 default, 1 abs, 2 rel
    broadcast: u8, // Broadcast enum value
}

fn mem_op(t: &MemT) -> Operand {
    let addr_sig =
        OperandSignature::from_value::<{ Mem::SIGNATURE_MEM_ADDR_TYPE_MASK }>(t.addr_type as u32);
    let m = if t.base_rt == RT_NONE {
        Mem::from_u64(t.disp as u64, t.size as u32, addr_sig)
    } else {
        let base_op = reg_op(t.base_rt, t.base_id);
        let base = base_op.as_::<asmkit::core::operand::BaseReg>();
        if t.index_rt != RT_NONE {
            let index_op = reg_op(t.index_rt, t.index_id);
            let index = index_op.as_::<asmkit::core::operand::BaseReg>();
            Mem::from_base_and_index_shift_disp(
                &base,
                &index,
                t.scale as u32,
                t.disp as i32,
                t.size as u32,
                addr_sig,
            )
        } else {
            Mem::from_base_and_disp(&base, t.disp as i32, t.size as u32, addr_sig)
        }
    };
    let m = if t.broadcast != 0 {
        let b = match t.broadcast {
            1 => Broadcast::B1To2,
            2 => Broadcast::B1To4,
            3 => Broadcast::B1To8,
            4 => Broadcast::B1To16,
            5 => Broadcast::B1To32,
            _ => Broadcast::B1To64,
        };
        m.clone_broadcasted(b)
    } else {
        m
    };
    m.0.0
}

fn mem_pool() -> Vec<MemT> {
    let mut v = Vec::new();
    let mut push = |base_rt: u8,
                    base_id: u8,
                    index_rt: u8,
                    index_id: u8,
                    scale: u8,
                    disp: i64,
                    size: u8,
                    addr_type: u8,
                    broadcast: u8| {
        v.push(MemT {
            base_rt,
            base_id,
            index_rt,
            index_id,
            scale,
            disp,
            size,
            addr_type,
            broadcast,
        });
    };
    // [base + 0]; rsp/r12 force SIB, rbp/r13 force a disp8.
    for (i, b) in [0u8, 1, 4, 5, 8, 12, 13].iter().enumerate() {
        push(
            RT_GP64,
            *b,
            RT_NONE,
            0,
            0,
            0,
            [0, 4, 8, 1, 2, 16, 32][i % 7],
            0,
            0,
        );
    }
    // [base + disp8-ish]
    for (i, (b, d)) in [
        (0u8, 8i64),
        (0, -8),
        (1, 127),
        (1, -128),
        (4, 16),
        (5, -16),
        (8, 64),
        (13, -64),
        (11, -1),
    ]
    .iter()
    .enumerate()
    {
        push(
            RT_GP64,
            *b,
            RT_NONE,
            0,
            0,
            *d,
            [4, 8, 0, 2, 1, 16, 32, 64, 10][i % 9],
            0,
            0,
        );
    }
    // [base + disp32]
    for (i, (b, d)) in [
        (0u8, 128i64),
        (0, -129),
        (1, 4096),
        (2, -4096),
        (3, 0x7fff_ffff),
        (6, -2_147_483_648),
        (7, 65536),
        (8, -100_000),
        (15, 0x1234_5678),
    ]
    .iter()
    .enumerate()
    {
        push(
            RT_GP64,
            *b,
            RT_NONE,
            0,
            0,
            *d,
            [8, 4, 0, 2, 1, 16, 32, 64, 6][i % 9],
            0,
            0,
        );
    }
    // [base + index*scale + disp]
    for (b, i, s, d) in [
        (0u8, 1u8, 0u8, 0i64),
        (0, 1, 1, 8),
        (3, 0, 2, 64),
        (4, 1, 0, 0),
        (12, 1, 0, -8),
        (13, 14, 3, 128),
        (8, 9, 3, -16),
        (2, 15, 2, 4096),
        (7, 6, 1, -1),
    ] {
        push(RT_GP64, b, RT_GP64, i, s, d, 8, 0, 0);
    }
    // [rip + disp32]
    for d in [0i64, 8, -8, 65536] {
        push(RT_PC, 0, RT_NONE, 0, 0, d, 8, 0, 0);
    }
    // Absolute (moffs) and base-less disp32 forms.
    push(RT_NONE, 0, RT_NONE, 0, 0, 0x123_4567, 8, 1, 0);
    push(RT_NONE, 0, RT_NONE, 0, 0, 0x234_5678, 4, 0, 0);
    // VSIB forms (vector index) for gathers/scatters.
    push(RT_GP64, 0, RT_VEC128, 1, 0, 0, 16, 0, 0);
    push(RT_GP64, 3, RT_VEC256, 2, 1, 16, 32, 0, 0);
    push(RT_GP64, 2, RT_VEC512, 3, 2, 64, 64, 0, 0);
    // Broadcast forms.
    for bc in 1u8..=6 {
        push(RT_GP64, 0, RT_NONE, 0, 0, 0, 4, 0, bc);
        push(RT_GP64, 1, RT_NONE, 0, 0, 8, 8, 0, bc);
    }
    v
}

/// VSIB-only pool for gather/scatter mnemonics: those are the only
/// instructions where a vector index is valid, and the baseline encoder
/// silently mis-encodes them with a plain GP-index/no-index memory operand.
fn vsib_pool() -> Vec<MemT> {
    let mut v = Vec::new();
    let mut push = |base: u8, idx_rt: u8, idx: u8, scale: u8, disp: i64, size: u8| {
        v.push(MemT {
            base_rt: RT_GP64,
            base_id: base,
            index_rt: idx_rt,
            index_id: idx,
            scale,
            disp,
            size,
            addr_type: 0,
            broadcast: 0,
        });
    };
    push(0, RT_VEC128, 1, 0, 0, 16);
    push(0, RT_VEC128, 0, 1, 16, 16);
    push(3, RT_VEC128, 7, 2, -16, 16);
    push(8, RT_VEC128, 15, 0, 64, 16);
    push(3, RT_VEC128, 1, 2, 0, 16);
    push(0, RT_VEC128, 7, 1, 32, 16);
    push(8, RT_VEC128, 8, 0, -64, 16);
    push(0, RT_VEC256, 2, 1, 16, 32);
    push(2, RT_VEC512, 3, 2, 64, 64);
    v
}

fn imm_pool() -> Vec<i64> {
    vec![
        0,
        1,
        127,
        -1,
        128,
        -128,
        -129,
        255,
        2,
        256,
        32767,
        32768,
        -32768,
        65535,
        5,
        -2,
        100,
        -1000,
        1000,
        63,
        0x7fff_ffff,
        -2_147_483_648,
        2_147_483_648,
        0xffff_ffff,
        0x1234_5678,
        4_294_967_296,
        0x1122_3344_5566_7788,
        -1,
    ]
}

fn pat_pool(p: Pat, mems: &[MemT], imms: &[i64]) -> Vec<Operand> {
    match p {
        Pat::Gp8Lo => [0u8, 1, 2, 3, 4, 5, 6, 7, 8, 9, 15]
            .iter()
            .map(|&i| reg_op(RT_GP8LO, i))
            .collect(),
        Pat::Gp16 => [0u8, 1, 2, 3, 4, 5, 6, 7, 8, 12, 13, 15]
            .iter()
            .map(|&i| reg_op(RT_GP16, i))
            .collect(),
        Pat::Gp32 => [0u8, 1, 2, 3, 4, 5, 6, 7, 8, 12, 13, 15]
            .iter()
            .map(|&i| reg_op(RT_GP32, i))
            .collect(),
        Pat::Gp64 => [0u8, 1, 2, 3, 4, 5, 6, 7, 8, 12, 13, 15]
            .iter()
            .map(|&i| reg_op(RT_GP64, i))
            .collect(),
        Pat::Vec128 => [0u8, 1, 2, 7, 8, 15, 16, 31]
            .iter()
            .map(|&i| reg_op(RT_VEC128, i))
            .collect(),
        Pat::Vec256 => [0u8, 1, 2, 7, 8, 15, 16, 31]
            .iter()
            .map(|&i| reg_op(RT_VEC256, i))
            .collect(),
        Pat::Vec512 => [0u8, 1, 2, 7, 8, 15, 16, 31]
            .iter()
            .map(|&i| reg_op(RT_VEC512, i))
            .collect(),
        Pat::Mask => [0u8, 1, 2, 3, 7]
            .iter()
            .map(|&i| reg_op(RT_MASK, i))
            .collect(),
        Pat::Mm => [0u8, 1, 2, 7].iter().map(|&i| reg_op(RT_MM, i)).collect(),
        Pat::St => [0u8, 1, 2, 7].iter().map(|&i| reg_op(RT_ST, i)).collect(),
        Pat::Tmm => [0u8, 1, 2, 7].iter().map(|&i| reg_op(RT_TMM, i)).collect(),
        Pat::SReg => [1u8, 2, 3, 4, 5, 6]
            .iter()
            .map(|&i| reg_op(RT_SREG, i))
            .collect(),
        Pat::CReg => [0u8, 2, 3, 4, 8]
            .iter()
            .map(|&i| reg_op(RT_CREG, i))
            .collect(),
        Pat::DReg => [0u8, 1, 2, 3, 7]
            .iter()
            .map(|&i| reg_op(RT_DREG, i))
            .collect(),
        Pat::Mem => mems.iter().map(mem_op).collect(),
        Pat::Imm => imms.iter().map(|&v| *imm(v).as_operand()).collect(),
        Pat::Label => vec![*Label::new().as_operand()],
        Pat::Sym => vec![],
    }
}

// ============================================================================
// Prefix/option variants for an accepted (mnemonic, operands) pair.
// ============================================================================
const LOCKABLE: &[&str] = &[
    "add", "or", "adc", "sbb", "and", "sub", "xor", "not", "neg", "inc", "dec", "xadd", "xchg",
    "btc", "btr", "bts", "cmpxchg",
];
const SEG_OK: &[&str] = &["mov", "xchg", "add", "xor", "or", "and", "sub", "cmp"];
const REP_OK: &[&str] = &["movs", "stos", "lods", "ins", "outs"];
const REPZ_OK: &[&str] = &["cmps", "scas"];

fn variants_for(mnem: &str, ops: &[Operand]) -> Vec<Opts> {
    // Mnemonic tags: "_er"/"_sae" mark embedded-rounding consts (EVEX.b is
    // baked into the const; L'L carries the rounding mode), "_mask"/"_maskz"
    // mark masking consts. The tags appear after the base name in any
    // combination: <base>[_mask|_maskz][_er|_sae].
    let (stem, is_er) = match mnem
        .strip_suffix("_er")
        .or_else(|| mnem.strip_suffix("_sae"))
    {
        Some(s) => (s, true),
        None => (mnem, false),
    };
    let is_maskz = stem.ends_with("_maskz");
    let is_mask = is_maskz || stem.ends_with("_mask");

    // Gathers/scatters are the only VSIB instructions; the baseline encodes
    // them all as EVEX, which requires a mask register (the encoder errors
    // with InvalidMasking otherwise). There are no _mask suffixed dyn
    // mnemonics for them, so force masked variants here.
    let is_gather = mnem.contains("gather") || mnem.contains("scatter");

    let mut v = Vec::new();
    if is_gather {
        for kid in [1u8, 3, 7] {
            v.push(Opts {
                k: Some(kid),
                ..Default::default()
            });
        }
    } else if is_er {
        // No plain variant: it is byte-identical to rn-sae (EVEX.b baked,
        // RC_RN = 0), and an _er record with er=none would be meaningless
        // for the replay side.
        let bases: Vec<Opts> = if is_mask {
            [1u8, 3, 7]
                .iter()
                .map(|&kid| Opts {
                    k: Some(kid),
                    ..Default::default()
                })
                .collect()
        } else {
            vec![Opts::default()]
        };
        for rc in 2u8..=5 {
            for b in &bases {
                let mut o = *b;
                o.er = rc;
                v.push(o);
            }
        }
    } else {
        // {z} with no mask register is reserved (EVEX.z=1, aaa=0 => #UD), so
        // _maskz forms are only emitted with an explicit mask.
        if !is_maskz {
            v.push(Opts::default());
        }
        if is_mask {
            for kid in [1u8, 3, 7] {
                v.push(Opts {
                    k: Some(kid),
                    ..Default::default()
                });
            }
        }
    }
    let first_is_mem = ops.first().map(|o| o.is_mem()).unwrap_or(false);
    let any_mem = ops.iter().any(|o| o.is_mem());
    if LOCKABLE.contains(&mnem) && first_is_mem {
        v.push(Opts {
            lock: true,
            ..Default::default()
        });
    }
    if SEG_OK.contains(&mnem) && any_mem {
        for sid in [5u8, 6] {
            v.push(Opts {
                seg: sid,
                ..Default::default()
            });
        }
    }
    if REP_OK.contains(&mnem) {
        v.push(Opts {
            rep: true,
            ..Default::default()
        });
    }
    if REPZ_OK.contains(&mnem) {
        v.push(Opts {
            rep: true,
            ..Default::default()
        });
        v.push(Opts {
            repnz: true,
            ..Default::default()
        });
    }
    v
}

// ============================================================================
// Shell-ordered product iteration over pool indices.
// ============================================================================
fn for_each_shell_tuple(lens: &[usize], mut f: impl FnMut(&[usize]) -> bool) {
    if lens.is_empty() {
        // Nullary instruction form: a single empty tuple.
        let _ = f(&[]);
        return;
    }
    fn rec(
        lens: &[usize],
        shell: usize,
        cur: &mut Vec<usize>,
        pos: usize,
        hit: &mut bool,
        f: &mut dyn FnMut(&[usize]) -> bool,
    ) -> bool {
        if pos == lens.len() {
            return !*hit || f(cur);
        }
        let hi = shell.min(lens[pos] - 1);
        for i in 0..=hi {
            cur[pos] = i;
            let old = *hit;
            if i == shell {
                *hit = true;
            }
            if !rec(lens, shell, cur, pos + 1, hit, f) {
                return false;
            }
            *hit = old;
        }
        true
    }
    let max_len = lens.iter().max().copied().unwrap_or(0);
    for shell in 0..max_len {
        let mut cur = vec![0usize; lens.len()];
        let mut hit = false;
        if lens.is_empty() {
            break;
        }
        if !rec(lens, shell, &mut cur, 0, &mut hit, &mut f) {
            break;
        }
    }
}

// ============================================================================
// Main generation loop.
// ============================================================================
struct Ctx {
    out: std::io::BufWriter<std::fs::File>,
    stats: Stats,
    max_per_form: usize,
    max_records: usize,
    verify: bool,
    panics: u64,
}

impl Ctx {
    fn write_record(&mut self, rec: &Record) -> bool {
        if self.max_records != 0 && self.stats.records >= self.max_records as u64 {
            return false;
        }
        if self.verify {
            if let Err(why) = verify::check(rec) {
                self.stats.verify_dropped += 1;
                if std::env::var_os("CORPUS_TRACE").is_some() {
                    let start = rec.instr_offset as usize;
                    let end = start + rec.instr_len as usize;
                    eprintln!(
                        "DROP {mnem} ops={:?} why={why} bytes={:02x?}",
                        rec.ops
                            .iter()
                            .map(|o| (o.kind, o.rt, o.id))
                            .collect::<Vec<_>>(),
                        &rec.block[start..end],
                        mnem = rec.mnem,
                    );
                }
                *self
                    .stats
                    .drop_reasons
                    .entry((rec.mnem.clone(), why))
                    .or_insert(0) += 1;
                return true;
            }
        }
        if rec.write(&mut self.out).is_err() {
            eprintln!("write failed");
            std::process::exit(1);
        }
        self.stats.records += 1;
        self.stats.bytes += rec.block.len() as u64;
        true
    }
}

fn make_record(
    mnem: &str,
    opcode: i64,
    opts: &Opts,
    ops: &[Operand],
    label_layout: u8,
    out: &EmitOut,
) -> Record {
    Record {
        mnem: mnem.to_string(),
        opcode,
        opts: *opts,
        ops: ops.iter().map(OpRec::from_operand).collect(),
        label_layout,
        label_bind_offset: out.label_bind_offset,
        instr_offset: out.instr_offset,
        instr_len: out.instr_len,
        block: out.block.clone(),
    }
}

fn gen_form(ctx: &mut Ctx, mnem: &'static str, form: &[Pat], mems: &[MemT], imms: &[i64]) {
    if form.iter().any(|p| *p == Pat::Sym) {
        ctx.stats.sym_forms_skipped += 1;
        return;
    }
    // Label forms: only arity-1 [Label] is supported by the label recipes.
    if form.iter().any(|p| *p == Pat::Label) {
        if form != [Pat::Label] {
            ctx.stats.mixed_label_skipped += 1;
            return;
        }
        for layout in [LL_SELF, LL_FAR_BACK, LL_FAR_FWD] {
            let label_op = *Label::new().as_operand();
            let ops = [label_op];
            let accepted =
                std::panic::catch_unwind(AssertUnwindSafe(|| Instruction::from_mnem(mnem, &ops)));
            ctx.stats.attempts += 1;
            let instr = match accepted {
                Ok(Ok(i)) => i,
                Ok(Err(_)) => continue,
                Err(_) => {
                    ctx.stats.panics += 1;
                    continue;
                }
            };
            ctx.stats.from_mnem_ok += 1;
            let real_ops = [instr.op0];
            let mut panics = 0u64;
            if let Some(out) = emit_record(
                &real_ops,
                instr.opcode,
                &Opts::default(),
                layout,
                &mut panics,
            ) {
                ctx.stats.panics += panics;
                ctx.stats.emit_ok += 1;
                let rec = make_record(
                    mnem,
                    instr.opcode,
                    &Opts::default(),
                    &real_ops,
                    layout,
                    &out,
                );
                let before = ctx.stats.records;
                if !ctx.write_record(&rec) {
                    return;
                }
                if ctx.stats.records > before {
                    ctx.stats.mnems_covered.insert(mnem);
                }
            }
        }
        return;
    }

    let pools: Vec<Vec<Operand>> = form.iter().map(|p| pat_pool(*p, mems, imms)).collect();
    if pools.iter().any(|p| p.is_empty()) {
        return;
    }
    let lens: Vec<usize> = pools.iter().map(|p| p.len()).collect();
    let mut accepted_this_form = 0usize;
    let mut attempts_this_form = 0usize;
    // Budget for forms that never produce a verified record (mis-encoded by
    // the baseline encoder or undecodable by iced): without it they would
    // burn their entire pool product.
    let attempt_budget = 4000usize;
    let cap = ctx.max_per_form;
    let mut stop = false;
    for_each_shell_tuple(&lens, |idx| {
        if stop || accepted_this_form >= cap || attempts_this_form >= attempt_budget {
            return false;
        }
        attempts_this_form += 1;
        let ops: Vec<Operand> = idx.iter().zip(&pools).map(|(&i, p)| p[i]).collect();
        let accepted =
            std::panic::catch_unwind(AssertUnwindSafe(|| Instruction::from_mnem(mnem, &ops)));
        ctx.stats.attempts += 1;
        let instr = match accepted {
            Ok(Ok(i)) => i,
            Ok(Err(_)) => return true,
            Err(_) => {
                ctx.stats.panics += 1;
                return true;
            }
        };
        ctx.stats.from_mnem_ok += 1;
        let real_ops: Vec<Operand> = ops.clone();
        for opts in variants_for(mnem, &real_ops) {
            let mut panics = 0u64;
            if let Some(out) = emit_record(&real_ops, instr.opcode, &opts, 0xFF, &mut panics) {
                ctx.stats.panics += panics;
                ctx.stats.emit_ok += 1;
                let rec = make_record(mnem, instr.opcode, &opts, &real_ops, 0xFF, &out);
                let before = ctx.stats.records;
                if !ctx.write_record(&rec) {
                    stop = true;
                    return false;
                }
                if ctx.stats.records > before {
                    // Only verified, actually-written records consume the
                    // per-form cap (a verify-drop must not starve the form).
                    accepted_this_form += 1;
                    ctx.stats.mnems_covered.insert(mnem);
                }
                if accepted_this_form >= cap {
                    return false;
                }
            } else {
                ctx.stats.panics += panics;
            }
        }
        true
    });
}

// ============================================================================
// Direct-construction extras (bypass from_mnem where it is too restrictive).
// ============================================================================
fn gen_direct(ctx: &mut Ctx) {
    // NOTE: high-byte registers (ah..bh) are intentionally absent. The
    // baseline's dynamic constructors only accept Gp8Lo, and the encoder has
    // no Gp8Hi id+4 mapping: `mov ah, ah` would silently encode as
    // `mov al, al`. There is nothing byte-faithful to record.

    // Size-qualified string ops: from_mnem("movs") only yields MOVS8, so the
    // 16/32/64-bit forms (and their REP variants) are constructed directly.
    let str_ops: &[(&str, i64)] = &[
        ("movs16", opcodes::MOVS16),
        ("movs32", opcodes::MOVS32),
        ("movs64", opcodes::MOVS64),
        ("stos16", opcodes::STOS16),
        ("stos32", opcodes::STOS32),
        ("stos64", opcodes::STOS64),
        ("lods16", opcodes::LODS16),
        ("lods32", opcodes::LODS32),
        ("lods64", opcodes::LODS64),
        ("cmps16", opcodes::CMPS16),
        ("cmps32", opcodes::CMPS32),
        ("cmps64", opcodes::CMPS64),
        ("scas16", opcodes::SCAS16),
        ("scas32", opcodes::SCAS32),
        ("scas64", opcodes::SCAS64),
        ("ins16", opcodes::INS16),
        ("ins32", opcodes::INS32),
        ("outs16", opcodes::OUTS16),
        ("outs32", opcodes::OUTS32),
    ];
    for (mnem, opc) in str_ops {
        for opts in [
            Opts::default(),
            Opts {
                rep: true,
                ..Default::default()
            },
            Opts {
                repnz: true,
                ..Default::default()
            },
        ] {
            let ops: Vec<Operand> = vec![];
            let mut panics = 0u64;
            if let Some(out) = emit_record(&ops, *opc, &opts, 0xFF, &mut panics) {
                ctx.stats.panics += panics;
                ctx.stats.emit_ok += 1;
                let rec = make_record(mnem, *opc, &opts, &ops, 0xFF, &out);
                let before = ctx.stats.records;
                if !ctx.write_record(&rec) {
                    return;
                }
                if ctx.stats.records > before {
                    ctx.stats.mnems_covered.insert(mnem);
                }
            } else {
                ctx.stats.panics += panics;
            }
        }
    }
}

// ============================================================================
// main
// ============================================================================
fn main() {
    let mut out_path = String::from("corpus.bin");
    let mut max_per_form = 12usize;
    let mut max_records = 0usize;
    let mut verify = true;
    let mut filter: Option<String> = None;
    let mut args = std::env::args().skip(1);
    while let Some(a) = args.next() {
        match a.as_str() {
            "--out" => out_path = args.next().expect("--out needs a value"),
            "--max-per-form" => {
                max_per_form = args
                    .next()
                    .expect("--max-per-form needs a value")
                    .parse()
                    .unwrap()
            }
            "--max-records" => {
                max_records = args
                    .next()
                    .expect("--max-records needs a value")
                    .parse()
                    .unwrap()
            }
            "--no-verify" => verify = false,
            "--mnem" => filter = Some(args.next().expect("--mnem needs a value")),
            other => {
                eprintln!("unknown arg: {other}");
                std::process::exit(2);
            }
        }
    }

    // Count panics quietly; print only the first few.
    let panic_count = std::sync::atomic::AtomicU64::new(0);
    std::panic::set_hook(Box::new(move |info| {
        let n = panic_count.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        if n < 3 {
            eprintln!("panic during emit: {info}");
        }
    }));

    let file = std::fs::File::create(&out_path).expect("cannot create output");
    let mut ctx = Ctx {
        out: std::io::BufWriter::new(file),
        stats: Stats::default(),
        max_per_form,
        max_records,
        verify,
        panics: 0,
    };
    ctx.out.write_all(MAGIC).unwrap();
    ctx.out.write_all(&0u32.to_le_bytes()).unwrap(); // flags
    ctx.out.write_all(&0u32.to_le_bytes()).unwrap(); // reserved

    let mems = mem_pool();
    let vsibs = vsib_pool();
    let imms = imm_pool();

    let mut done = false;
    for (ri, recipe) in RECIPES.iter().enumerate() {
        if ri % 500 == 0 {
            eprintln!(
                "... recipe {ri}/{} ({} records)",
                RECIPES.len(),
                ctx.stats.records
            );
        }
        if let Some(f) = &filter {
            if !recipe.mnem.contains(f.as_str()) {
                continue;
            }
        }
        // Gathers/scatters are the only VSIB instructions; restrict their
        // memory pool so the form cap is not consumed by mis-encoded
        // plain-memory combos (which the verifier would drop anyway).
        let mems_sel: &[MemT] = if recipe.mnem.contains("gather") || recipe.mnem.contains("scatter")
        {
            &vsibs
        } else {
            &mems
        };
        for form in recipe.forms {
            gen_form(&mut ctx, recipe.mnem, form, mems_sel, &imms);
            if max_records != 0 && ctx.stats.records >= max_records as u64 {
                done = true;
                break;
            }
        }
        if done {
            break;
        }
    }
    if !done && filter.is_none() {
        gen_direct(&mut ctx);
    }

    use std::io::Write as _;
    ctx.out.flush().unwrap();
    let s = &ctx.stats;
    eprintln!("=== corpus_gen stats ===");
    eprintln!("records written : {}", s.records);
    eprintln!("distinct mnems  : {}", s.mnems_covered.len());
    eprintln!("instruction bytes: {}", s.bytes);
    eprintln!("attempts        : {}", s.attempts);
    eprintln!("from_mnem ok    : {}", s.from_mnem_ok);
    eprintln!("emit ok         : {}", s.emit_ok);
    eprintln!("panics          : {}", s.panics);
    eprintln!("verify dropped  : {}", s.verify_dropped);
    eprintln!("sym forms skipped: {}", s.sym_forms_skipped);
    eprintln!("mixed-label skipped: {}", s.mixed_label_skipped);
    if !s.drop_reasons.is_empty() {
        eprintln!("--- verify drop reasons (top 40) ---");
        let mut reasons: Vec<_> = s.drop_reasons.iter().collect();
        reasons.sort_by_key(|(_, c)| std::cmp::Reverse(**c));
        for ((mnem, why), c) in reasons.iter().take(100) {
            eprintln!("  {c:6} {mnem:30} {why}");
        }
    }
}
