#!/usr/bin/env python3
"""Extract per-mnemonic operand recipes from the baseline's dynamic x86 API.

Parses src/x86/features/_DYN.rs of the extracted baseline tree:

1. Every `Instruction::<mnem>` constructor body is scanned for operand-type
   guard lines (`if op0.is_gp32() && op1.is_mem() { ... }`). Each guard yields
   one accepted operand pattern tuple.
2. The `Instruction::from_mnem` dispatch table is scanned to map each mnemonic
   string (plus operand count) to the constructor it calls.

The join of the two is emitted as a Rust source file (`corpus_recipes.rs`)
containing a static `RECIPES` table consumed by `corpus_gen.rs`.

Usage: extract_recipes.py <path-to-_DYN.rs> <output-rs>
"""

import re
import sys
from collections import OrderedDict

# Maps the full text of an operand check (sans `opN.` prefix) to a pattern tag.
PAT_MAP = {
    "is_reg_group_of(RegGroup::X86MM)": "Mm",
    "is_reg_group_of(RegGroup::X86St)": "St",
    "is_reg_group_of(RegGroup::X86Tmm)": "Tmm",
    "is_reg_group_of(RegGroup::X86SReg)": "SReg",
    "is_reg_group_of(RegGroup::X86CReg)": "CReg",
    "is_reg_group_of(RegGroup::X86DReg)": "DReg",
    "is_reg_type_of(RegType::Gp8Lo)": "Gp8Lo",
    "is_reg_type_of(RegType::Gp16)": "Gp16",
    "is_gp32()": "Gp32",
    "is_gp64()": "Gp64",
    "is_vec128()": "Vec128",
    "is_vec256()": "Vec256",
    "is_vec512()": "Vec512",
    "is_mask()": "Mask",
    "is_mem()": "Mem",
    "is_imm()": "Imm",
    "is_label()": "Label",
    "is_sym()": "Sym",
}

CTOR_RE = re.compile(
    r"    pub fn (\w+)\(([^)]*)\) -> Result<Self, AsmError> \{(.*?)\n    \}\n", re.S
)
COND_RE = re.compile(
    r"if (op\d\.is_\w+(?:\([^)]*\))?(?: && op\d\.is_\w+(?:\([^)]*\))?)*) \{"
)
TERM_RE = re.compile(r"op(\d)\.(is_\w+(?:\([^)]*\))?)")

ARM_RE = re.compile(r'^ {12}"([a-z0-9_]+)" => \{\n(.*?)^ {12}\},', re.S | re.M)
CALL_RE = re.compile(
    r"if (?:ops\.len\(\) == (\d+)|ops\.is_empty\(\)) \{\s*\n\s+Self::(\w+)\("
)


def parse_constructors(src):
    """name -> list of pattern tuples (in declaration order)."""
    ctors = OrderedDict()
    warnings = []
    for m in CTOR_RE.finditer(src):
        name, args, body = m.group(1), m.group(2), m.group(3)
        if name == "from_mnem":
            continue
        nargs = 0 if not args.strip() else len(args.split(","))
        forms = []
        for cm in COND_RE.finditer(body):
            cond = cm.group(1)
            pats = [None] * nargs
            ok = True
            for t in TERM_RE.finditer(cond):
                idx, chk = int(t.group(1)), t.group(2)
                p = PAT_MAP.get(chk)
                if p is None or idx >= nargs or pats[idx] is not None:
                    ok = False
                    break
                pats[idx] = p
            if not ok or any(p is None for p in pats):
                warnings.append(f"{name}: skipped guard: {cond}")
                continue
            forms.append(tuple(pats))
        if not forms and nargs == 0 and "return Ok(Self { opcode:" in body:
            forms.append(())
        ctors[name] = forms
    return ctors, warnings


def parse_from_mnem(src, ctors, warnings):
    """List of (mnemonic, arity, ctor, forms) preserving table order."""
    fm = src.index("pub fn from_mnem")
    recipes = []
    for m in ARM_RE.finditer(src, fm):
        mnem, body = m.group(1), m.group(2)
        for lm in CALL_RE.finditer(body):
            arity = int(lm.group(1)) if lm.group(1) is not None else 0
            ctor = lm.group(2)
            forms = ctors.get(ctor)
            if forms is None:
                warnings.append(f'"{mnem}": constructor {ctor} not parsed')
                continue
            forms = [f for f in forms if len(f) == arity]
            seen, uforms = set(), []
            for f in forms:
                if f not in seen:
                    seen.add(f)
                    uforms.append(f)
            if uforms:
                recipes.append((mnem, arity, ctor, uforms))
    return recipes


def main():
    dyn_path, out_path = sys.argv[1], sys.argv[2]
    src = open(dyn_path).read()

    ctors, warnings = parse_constructors(src)
    recipes = parse_from_mnem(src, ctors, warnings)

    pats = sorted({p for (_, _, _, forms) in recipes for f in forms for p in f})
    with open(out_path, "w") as out:
        out.write("// Generated by meta/difftest/extract_recipes.py from the baseline\n")
        out.write("// src/x86/features/_DYN.rs. Do not edit by hand.\n\n")
        out.write("#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]\n")
        out.write("pub enum Pat {\n")
        for p in pats:
            out.write(f"    {p},\n")
        out.write("}\n\n")
        out.write("pub struct Recipe {\n")
        out.write("    pub mnem: &'static str,\n")
        out.write("    pub ctor: &'static str,\n")
        out.write("    pub forms: &'static [&'static [Pat]],\n")
        out.write("}\n\n")
        out.write("pub static RECIPES: &[Recipe] = &[\n")
        for mnem, _arity, ctor, forms in recipes:
            out.write(f'    Recipe {{ mnem: "{mnem}", ctor: "{ctor}", forms: &[\n')
            for f in forms:
                inner = ", ".join(f"Pat::{p}" for p in f)
                out.write(f"        &[{inner}],\n")
            out.write("    ]},\n")
        out.write("];\n")

    nforms = sum(len(r[3]) for r in recipes)
    mnems = {r[0] for r in recipes}
    print(
        f"extract_recipes: {len(recipes)} (mnemonic, arity) entries, "
        f"{len(mnems)} distinct mnemonics, {nforms} accepted forms, "
        f"{len(warnings)} warnings",
        file=sys.stderr,
    )
    for w in warnings[:20]:
        print(f"  warning: {w}", file=sys.stderr)
    if len(warnings) > 20:
        print(f"  ... and {len(warnings) - 20} more", file=sys.stderr)


if __name__ == "__main__":
    main()
