pub trait X86ADXEmitter: Emitter {
    /// Emits `ADCX32RR` (`ADCX`). Performs an unsigned addition of the destination operand (first operand), the source operand (second operand) and the carry-flag (CF) and stores the result in the destination operand. The destination operand is a general-purpose register, whereas the source operand can be a general-purpose register or memory location. The state of CF can represent a carry from a previous addition. The instruction sets the CF flag with the carry generated by the unsigned addition of the operands.
    /// Reference: [Intel x86 docs for ADCX](https://www.felixcloutier.com/x86/ADCX.html)
    fn adcx32rr(&mut self,op0: impl OperandCast,op1: impl OperandCast) -> () {
        self.emit(ADCX32RR, op0.as_operand(),op1.as_operand(),&NOREG /* op2 */,&NOREG /* op3 */)
    }
    /// Emits `ADCX32RM` (`ADCX`). Performs an unsigned addition of the destination operand (first operand), the source operand (second operand) and the carry-flag (CF) and stores the result in the destination operand. The destination operand is a general-purpose register, whereas the source operand can be a general-purpose register or memory location. The state of CF can represent a carry from a previous addition. The instruction sets the CF flag with the carry generated by the unsigned addition of the operands.
    /// Reference: [Intel x86 docs for ADCX](https://www.felixcloutier.com/x86/ADCX.html)
    fn adcx32rm(&mut self,op0: impl OperandCast,op1: impl OperandCast) -> () {
        self.emit(ADCX32RM, op0.as_operand(),op1.as_operand(),&NOREG /* op2 */,&NOREG /* op3 */)
    }
    /// Emits `ADCX64RR` (`ADCX`). Performs an unsigned addition of the destination operand (first operand), the source operand (second operand) and the carry-flag (CF) and stores the result in the destination operand. The destination operand is a general-purpose register, whereas the source operand can be a general-purpose register or memory location. The state of CF can represent a carry from a previous addition. The instruction sets the CF flag with the carry generated by the unsigned addition of the operands.
    /// Reference: [Intel x86 docs for ADCX](https://www.felixcloutier.com/x86/ADCX.html)
    fn adcx64rr(&mut self,op0: impl OperandCast,op1: impl OperandCast) -> () {
        self.emit(ADCX64RR, op0.as_operand(),op1.as_operand(),&NOREG /* op2 */,&NOREG /* op3 */)
    }
    /// Emits `ADCX64RM` (`ADCX`). Performs an unsigned addition of the destination operand (first operand), the source operand (second operand) and the carry-flag (CF) and stores the result in the destination operand. The destination operand is a general-purpose register, whereas the source operand can be a general-purpose register or memory location. The state of CF can represent a carry from a previous addition. The instruction sets the CF flag with the carry generated by the unsigned addition of the operands.
    /// Reference: [Intel x86 docs for ADCX](https://www.felixcloutier.com/x86/ADCX.html)
    fn adcx64rm(&mut self,op0: impl OperandCast,op1: impl OperandCast) -> () {
        self.emit(ADCX64RM, op0.as_operand(),op1.as_operand(),&NOREG /* op2 */,&NOREG /* op3 */)
    }
    /// Emits `ADOX32RR` (`ADOX`). Performs an unsigned addition of the destination operand (first operand), the source operand (second operand) and the overflow-flag (OF) and stores the result in the destination operand. The destination operand is a general-purpose register, whereas the source operand can be a general-purpose register or memory location. The state of OF represents a carry from a previous addition. The instruction sets the OF flag with the carry generated by the unsigned addition of the operands.
    /// Reference: [Intel x86 docs for ADOX](https://www.felixcloutier.com/x86/ADOX.html)
    fn adox32rr(&mut self,op0: impl OperandCast,op1: impl OperandCast) -> () {
        self.emit(ADOX32RR, op0.as_operand(),op1.as_operand(),&NOREG /* op2 */,&NOREG /* op3 */)
    }
    /// Emits `ADOX32RM` (`ADOX`). Performs an unsigned addition of the destination operand (first operand), the source operand (second operand) and the overflow-flag (OF) and stores the result in the destination operand. The destination operand is a general-purpose register, whereas the source operand can be a general-purpose register or memory location. The state of OF represents a carry from a previous addition. The instruction sets the OF flag with the carry generated by the unsigned addition of the operands.
    /// Reference: [Intel x86 docs for ADOX](https://www.felixcloutier.com/x86/ADOX.html)
    fn adox32rm(&mut self,op0: impl OperandCast,op1: impl OperandCast) -> () {
        self.emit(ADOX32RM, op0.as_operand(),op1.as_operand(),&NOREG /* op2 */,&NOREG /* op3 */)
    }
    /// Emits `ADOX64RR` (`ADOX`). Performs an unsigned addition of the destination operand (first operand), the source operand (second operand) and the overflow-flag (OF) and stores the result in the destination operand. The destination operand is a general-purpose register, whereas the source operand can be a general-purpose register or memory location. The state of OF represents a carry from a previous addition. The instruction sets the OF flag with the carry generated by the unsigned addition of the operands.
    /// Reference: [Intel x86 docs for ADOX](https://www.felixcloutier.com/x86/ADOX.html)
    fn adox64rr(&mut self,op0: impl OperandCast,op1: impl OperandCast) -> () {
        self.emit(ADOX64RR, op0.as_operand(),op1.as_operand(),&NOREG /* op2 */,&NOREG /* op3 */)
    }
    /// Emits `ADOX64RM` (`ADOX`). Performs an unsigned addition of the destination operand (first operand), the source operand (second operand) and the overflow-flag (OF) and stores the result in the destination operand. The destination operand is a general-purpose register, whereas the source operand can be a general-purpose register or memory location. The state of OF represents a carry from a previous addition. The instruction sets the OF flag with the carry generated by the unsigned addition of the operands.
    /// Reference: [Intel x86 docs for ADOX](https://www.felixcloutier.com/x86/ADOX.html)
    fn adox64rm(&mut self,op0: impl OperandCast,op1: impl OperandCast) -> () {
        self.emit(ADOX64RM, op0.as_operand(),op1.as_operand(),&NOREG /* op2 */,&NOREG /* op3 */)
    }
}
